# **<font color=#ffffff>Provider Segmentation**
フレンチ • 提供者のセグメンテーション!! • 2025

<font color=#ffffff>
<b>1st Framework - Aug 4, 2025 • 10:58 AM (Process Draft Step 1 - Step 11)</b>

<b>2nd Framework - Aug 25, 2025 • 05:36 PM (After 2nd Internship Presentation)</b>

<b>3rd Framework - Aug 26, 2025 • 11:07 AM (From Step 1 to Step 2.2)</b> 

<b>4th Framework - Aug 27, 2025 • 02:00 PM (Step 2.3)</b>

<b>5th Framework - Aug 28, 2025 • 11:47 PM (Step 2.3 Numerical - Step 3)</b>

<b>6th Framework - Aug 29, 2025 • 09:11 AM (Step 3.1 Finish Handling Missing Value)</b>

<b>7th Framework - Sep 1, 2025 (Step 3.2 - Step 3.5 about to delete professional_id 0 and 300)</b>

<b>8th Framework - Sep 3, 2025 • 04:26 PM (Step 3.5 - Step 4.1.1)</b>

<b>9th Framework - Sep 4, 2025 • 11:28 AM (Step 4.1.2 - Step 4.4)</b>

<b>10th Framework - Sep 5, 2025 • 10:13 AM (Step 4.5)</b>

<b>11th Framework - Sep 8, 2025 • 09:46 AM (Step 4.6 - Finished!)</b>

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/image.png?raw=true" width="500">

<div style="border-radius:10px; padding:15px; background-color:rgb(256,12,84); font-size:100%; text-align:left; color:#ffffff;">

## <b><font color=#ffffff>Objectives</font></b>

<font color=#ffffff>

  <h4 align="left"><b>1st Phase - Exploratory Data Analysis</b></h4>
  <ul>
    <li><b>Exploratory Data Analysis (EDA)</b>: Visualizes data to understand its main features, find patterns and discover how different parts of data are connected.</li>
    <li><b>Data Cleaning & Transformation</b>: Clean the dataset by handling missing values, duplicates, and outliers, preparing it for effective clustering.</li>
    <li><b>Feature Engineering</b>: Develop new features based on the booking data and provider's behavior data to create a service provider centric dataset, setting the foundation for Provider Segmentation.</li>
    <li><b>Data Preprocessing</b>: Undertake feature scaling and dimensionality reduction to streamline the data (if necessary), enhancing the efficiency of the clustering process.</li>
  </ul>

  <h4 align="left"><b>2nd Phase - Data Modeling & Analysis</b></h4>
  <ul>
    <li><b>Provider Segmentation using K-Means Clustering</b>: Segment service providers into distinct groups using K-means, facilitating targeted marketing and personalized strategies.</li>
    <li><b>Cluster Analysis & Evaluation</b>: Analyze and profile each cluster to develop targeted marketing strategies and assess the quality of the clusters formed.</li>
    <li><b>Experimentation</b>: Implementing other clustering models such as Hierarchical Clustering, DBSCAN, etc. to find the best model for segmentation of providers.</li>
  </ul>

</div>


<a id="contents_table"></a>

<div style="border-radius:10px; padding: 15px; background-color:#10041c; font-size:100%; text-align:left">

## <b><font color=#ffffff>Table of Contents</font></b>

<font color=#ffffff>

<!-- - [Popular Services](#popular_services)
     - [Booking Geographic Distribution](#booking_geographic)
     - [Cancellation Insights](#cancellation_insights)
     - [Numerical Variables](#numerical_variables) -->
<!-- - [Booking Status](#booking_status) -->
<!-- - [Booking Trends](#booking_trends) -->

**1st Phase - Exploratory Data Analysis (Data Cleaing & Transformation + Feature Engineering)**
* [Step 1 | Setup and Initialization](#setup)
    - [Step 1.1 | Importing Necessary Libraries](#libraries) 
    - [Step 1.2 | Loading the Dataset](#load_dataset)
    - [Step 1.3 | Dataset Description](#data_description)
* [Step 2 | Exploratory Data Analysis](#exploratory_analysis) 
    - [Step 2.1 | Dataset Overview](#overview) 
    - [Step 2.2 | Summary Statistics](#statistics)
    - [Step 2.3 | Data Visualization](#visualizations)
        - [Univariate Analysis (Single Variable)](#univariate)
        - [Bivariate Analysis (Two Variable)](#bivariate)   
        - [Time-based Analysis](#time-based)
* [Step 3 | Data Cleaning & Transformation](#data_cleaning)
    - [Step 3.1 | Handling Missing Values](#missing_values)
    - [Step 3.2 | Handling Duplicates](#duplicates)
    - [Step 3.3 | Treating Cancelled Bookings](#cancelled_cleaning)
    - [Step 3.4 | Correcting Date Anomalies](#date_cleaning)
    - [Step 3.5 | Ensuring Data Consistency](#data_consistency)
        - [Same-day Inconsistency](#sameday_inconsistency)
        - [Status Inconsistency](#status_inconsistency)
        - [Geographic Inconsistency](#geographic_inconsistency)
        - [IDs Inconsistency](#id_inconsistency)
    - [Step 3.6 | Outlier Treatment](#outlier_cleaning)
* [Step 4 | Feature Engineering](#feature_engineering)
    - [Step 4.1 | RFM Features](#rfm_features)
        - [Step 4.1.1 | Recency (R)](#recency) 
        - [Step 4.1.2 | Frequency (F)](#frequency)
        - [Step 4.1.3 | Monetary (M)](#monetary)
    - [Step 4.2 | Service Type Diversity](#type_diversity)
    - [Step 4.3 | Behavioral Features](#behavioral_features)
    - [Step 4.4 | Cancellation Insights](#cancellation_insights) 
    - [Step 4.5 | Seasonality & Trends](#seasonality_trends) 
    - [Step 4.6 | Advanced Provider Features](#advanced_features) 
    - [Step 4.7 | Export Feature Engineer Data](#export_features) 
        - [Provider Dataset Description](#provider_description)
* [Step 5 | Data Preparation for Clustering Models](#data_preparation)


**2nd Phase - Data Modeling & Analysis (Outdated Pipeline)**
* [Step 6 | Outlier Detection and Treatment](#outlier_detection)
* [Step 7 | Correlation Analysis](#correlation)
* [Step 8 | Feature Scaling](#scaling)
* [Step 9 | Dimensionality Reduction](#pca)
* [Step 10 | K-Means Clustering](#kmeans) 
    - [Step 10.1 | Determining the Optimal Number of Clusters](#optimal_k) 
        - [Step 10.1.1 | Elbow Method](#elbow)
        - [Step 10.1.2 | Silhouette Method](#silhouette)
    - [Step 10.2 | Clustering Model - K-means](#kmeans_model)
* [Step 11 | Clustering Evaluation](#evaluation)  
    - [Step 11.1 | 3D Visualization of Top Principal Components](#3d_visualization)
    - [Step 11.2 | Cluster Distribution Visualization](#cluster_distributuion) 
    - [Step 11.3 | Evaluation Metrics](#evaluations_metrics)
* [Step 12 | Cluster Analysis and Profiling](#profiling)
    - [Step 12.1 | Radar Chart Approach](#radar_chart)
    - [Step 12.2 | Histogram Chart Approach](#histogram)

<a id="setup"></a>

## <b><span style='color:#ffa705'>Step 1 |</span><span style='color:#ffffff'> Setup and Initialization</span></b>
⬆️ [Table of Contents](#contents_table)

<a id="libraries"></a>

### <b><span style='color:#ffa705'>Step 1.1 |</span><span style='color:#ffffff'> Importing Necessary Libraries</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>
Import all necessary libraries that will be use throughout the project.

This includes libraries for data manipulation, data visualization, and others based on the specific needs of the project.

In [1]:
# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import geopandas as gpd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from matplotlib.colors import LinearSegmentedColormap
from matplotlib import colors as mcolors
from scipy.stats import linregress
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from yellowbrick.cluster import KElbowVisualizer, SilhouetteVisualizer
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
from sklearn.cluster import KMeans
from tabulate import tabulate
from collections import Counter

%matplotlib inline

In [2]:
# Inintialize Plotly for use in the notebook
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

In [3]:
# Configure Seaborn plot styles: Set background color and use dark grid
sns.set(rc={'axes.facecolor': '#fcf0dc'}, style='darkgrid')

In [4]:
# Display all columns of booking_raw without truncation
pd.set_option('display.max_columns', None)

<a id="load_dataset"></a>

### <b><span style='color:#ffa705'>Step 1.2 |</span><span style='color:#ffffff'> Loading the Dataset</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

Next, load the booking and provider's behavior datasets into a pandas DataFrame which will facilitate easy manipulation and analysis.

In [5]:
data = "C:\\Users\\Christopher French\\Downloads\\ビニート\\16-24_internship_project\\data\\booking_raw.csv"

df = pd.read_csv(data)

In [6]:
df.head()

booking_id  user_id  is_new_customer  user_place_id  \
0         23    31251                1              0   
1         24        3                1              0   
2         25        3                0              0   
3         26        3                0              0   
4         27        3                0              0   

                           place_size       service_name sub_service_name  \
0  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด              NaN   
1  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
2  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
3  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด              NaN   
4  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   

  extra_service   province district         booking_date        cleaning_date  \
0           NaN  เชียงใหม่      NaN  2016-03-23 08:50:10  2016-03-26 13:00:00   
1           NaN  เชียงใหม่      NaN  2016-03-24 21:14:38  2016-03-28 13:00:00   
2           NaN  เชียงใหม่      NaN  2016-03-26 20:56:23  2016-03-31 17:00:00   
3           NaN  เชียงใหม่      NaN  2016-03-26 20:58:36  2016-03-31 13:00:00   
4           NaN  เชียงใหม่      NaN  2016-03-26 21:04:26  2016-04-01 13:00:00   

   is_sameday  work_hour  additional_hour  total_price  discount_cost  \
0           0        2.0              0.0        400.0            0.0   
1           0        2.5              0.0        500.0            0.0   
2           0        2.5              0.0        500.0            0.0   
3           0        2.0              0.0        400.0            0.0   
4           0        2.5              0.0        500.0            0.0   

   credit_discount_cost promo_code  discount_pct booking_status cancel_reason  \
0                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
1                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
2                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
3                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
4                   0.0        NaN           NaN      เสร็จสิ้น           NaN   

   professional_id  selected_professional_id  is_new_professional  rating  \
0                8                         0                    1     4.0   
1                5                         0                    1     NaN   
2                7                         0                    0     5.0   
3                7                         0                    0     5.0   
4                8                         0                    0     5.0   

  problem  is_claimed_booking  
0     NaN                   0  
1     NaN                   0  
2     NaN                   0  
3     NaN                   0  
4     NaN                   0

<a id="data_description"></a>

### <b><span style='color:#ffa705'>Step 1.3 |</span><span style='color:#ffffff'> Dataset Description</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color:#10041c; font-size:100%; text-align:left">

| __Features__              | __Description__ |
|     :---                  |       :---      |      
| __booking_id__            | Code representing each unique booking transaction. |
| __user_id__               | Uniquely identifier assigned to each customer. |
| __is_new_customer__       | Indicates if the booking was made by a first-time customer (1 = new, 0 = old). |
| __user_place_id__         | Unique identifier of the customer’s place of residence. |
| __place_size__            | Size/type of place. |
| __service_name__          | Main cleaning service requested. |
| __sub_service_name__      | Sub-service category under the main cleaning service. |
| __extra_service__         | Any additional cleaning services requested. |
| __province__              | Province where the service is booked. |
| __district__              | District where the service is booked. |
| __booking_date__          | Date and time when the booking was made. |
| __cleaning_date__         | Scheduled date and time for the service. |
| __is_sameday__            | Indicates if booking and cleaning service happen on the same day (1 = yes, 0 = no). |
| __work_hour__             | Number of cleaning hours booked. |
| __additional_hour__       | Number of additional cleaning hours requested. |
| __total_price__           | Total service price before discounts. |
| __discount_cost__         | Discount applied. |
| __credit_discount_cost__  | Discount from credits applied. |
| __promo_code__            | Promotional code applied to the booking. |
| __discount_pct__          | Discount percentage applied. |
| __booking_status__        | Current booking status (e.g., completed, canceled). |
| __cancel_reason__         | Reason for cancellation (if booking was canceled). |
| __professional_id__       | ID of the service provider assigned to the job. |
| __selected_professional_id__ | ID of the service provider specifically chosen by the customer (if any). |
| __is_new_professional__   | Indicates if the assigned service provider is new (1 = new, 0 = old). |
| __rating__                | Customer’s rating of the service (if provided). |
| __problem__               | Reported issues related to the booking / after service. |
| __is_claimed_booking__    | Indicates if the booking was claimed by service provider (1 = claimed, 0 = unclaimed). |


<a id="exploratory_analysis"></a>

## <b><span style='color:#ffa705'>Step 2 |</span><span style='color:#ffffff'> Exploratory Data Analysis</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>
We need to gain a thorough understanding of the dataset before proceeding to the data cleaning and transformation stages.

<a id="overview"></a>

### <b><span style='color:#ffa705'>Step 2.1 |</span><span style='color:#ffffff'> Dataset Overview</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>
Perform a preliminary analysis to understand the structure and types of data columns.

In [7]:
df.head(10)

booking_id  user_id  is_new_customer  user_place_id  \
0         23    31251                1              0   
1         24        3                1              0   
2         25        3                0              0   
3         26        3                0              0   
4         27        3                0              0   
5         28       11                1              0   
6         29        3                0              0   
7         30        3                0              0   
8         31        3                0              0   
9         32        3                0              0   

                           place_size       service_name sub_service_name  \
0  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด              NaN   
1  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
2  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
3  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด              NaN   
4  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
5                            สำนักงาน  บริการทำความสะอาด              NaN   
6  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
7  คอนโด 1 ห้องนอน (ไม่เกิน 50 ตร.ม.)  บริการทำความสะอาด              NaN   
8  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด              NaN   
9  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด              NaN   

  extra_service   province district         booking_date        cleaning_date  \
0           NaN  เชียงใหม่      NaN  2016-03-23 08:50:10  2016-03-26 13:00:00   
1           NaN  เชียงใหม่      NaN  2016-03-24 21:14:38  2016-03-28 13:00:00   
2           NaN  เชียงใหม่      NaN  2016-03-26 20:56:23  2016-03-31 17:00:00   
3           NaN  เชียงใหม่      NaN  2016-03-26 20:58:36  2016-03-31 13:00:00   
4           NaN  เชียงใหม่      NaN  2016-03-26 21:04:26  2016-04-01 13:00:00   
5           NaN  เชียงใหม่      NaN  2016-03-30 14:38:38  2016-04-01 07:30:00   
6           NaN  เชียงใหม่      NaN  2016-03-30 15:15:28  2016-04-08 14:00:00   
7           NaN  เชียงใหม่      NaN  2016-04-02 11:11:39  2016-04-04 14:00:00   
8           NaN  เชียงใหม่      NaN  2016-04-02 11:15:12  2016-04-05 10:00:00   
9           NaN  เชียงใหม่      NaN  2016-04-02 11:17:28  2016-04-07 14:00:00   

   is_sameday  work_hour  additional_hour  total_price  discount_cost  \
0           0        2.0              0.0        400.0            0.0   
1           0        2.5              0.0        500.0            0.0   
2           0        2.5              0.0        500.0            0.0   
3           0        2.0              0.0        400.0            0.0   
4           0        2.5              0.0        500.0            0.0   
5           0        1.5              0.0        250.0           50.0   
6           0        2.5              0.0        500.0            0.0   
7           0        2.5              0.0        500.0            0.0   
8           0        2.0              0.0        400.0            0.0   
9           0        2.0              0.0        400.0            0.0   

   credit_discount_cost promo_code  discount_pct booking_status cancel_reason  \
0                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
1                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
2                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
3                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
4                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
5                   0.0     SAVE20          20.0      เสร็จสิ้น           NaN   
6                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
7                   0.0        NaN           NaN         ยกเลิก           NaN   
8                   0.0        NaN           NaN      เสร็จสิ้น           NaN   
9                   

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1135060 entries, 0 to 1135059
Data columns (total 28 columns):
 #   Column                    Non-Null Count    Dtype  
---  ------                    --------------    -----  
 0   booking_id                1135060 non-null  object 
 1   user_id                   1135060 non-null  int64  
 2   is_new_customer           1135060 non-null  int64  
 3   user_place_id             1135060 non-null  int64  
 4   place_size                1109181 non-null  object 
 5   service_name              1135060 non-null  object 
 6   sub_service_name          26417 non-null    object 
 7   extra_service             38345 non-null    object 
 8   province                  1135060 non-null  object 
 9   district                  1055083 non-null  object 
 10  booking_date              1135060 non-null  object 
 11  cleaning_date             1122742 non-null  object 
 12  is_sameday                1135060 non-null  int64  
 13  work_hour                 1

<b>Inferences</b>

<font color=#ffffff>
The dataset consists of 1,135,060 entries and 28 columns.

<a id="statistics"></a>

### <b><span style='color:#ffa705'>Step 2.2 |</span><span style='color:#ffffff'> Summary Statistics</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>
Now, we're going to generate summary statistics to gain initial insights into the data distribution.

In [9]:
# Summary statistics for numerical variables
df.describe().T

count           mean           std     min  \
user_id                   1135060.0  140907.308184  99539.725507     1.0   
is_new_customer           1135060.0       0.128785      0.334962     0.0   
user_place_id             1135060.0  106770.395685  84117.169406     0.0   
is_sameday                1135060.0       0.127385      0.333404     0.0   
work_hour                 1135060.0       3.116785      1.398128     0.0   
additional_hour           1135060.0       0.026330      0.196581     0.0   
total_price               1135060.0     732.850109    277.588427 -1140.0   
discount_cost             1135060.0      30.905815     46.477370     0.0   
credit_discount_cost      1135060.0       2.431315     15.504882     0.0   
discount_pct               627266.0       7.319031      5.921336     0.0   
professional_id           1135060.0    5223.179458   3550.103478     0.0   
selected_professional_id  1135060.0    2129.143497   3172.532866     0.0   
is_new_professional       1135060.0       0.006221      0.078626     0.0   
rating                     285103.0       4.897730      0.468229     0.5   
is_claimed_booking        1135060.0       0.000132      0.011495     0.0   

                              25%       50%        75%         max  
user_id                   54733.0  129205.0  212702.00   395520.00  
is_new_customer               0.0       0.0       0.00        1.00  
user_place_id             34078.0   89672.0  167293.25  2214890.00  
is_sameday                    0.0       0.0       0.00        1.00  
work_hour                     2.0       3.0       4.00       12.00  
additional_hour               0.0       0.0       0.00        7.00  
total_price                 520.0     650.0     912.00    10000.00  
discount_cost                 0.0      25.0      50.00     1600.00  
credit_discount_cost          0.0       0.0       0.00     1780.48  
discount_pct                  5.0       7.0       9.00      100.00  
professional_id            2039.0    5193.0    8133.00    12719.00  
selected_professional_id      0.0       0.0    3769.00    12669.00  
is_new_professional           0.0       0.0       0.00        1.00  
rating                        5.0       5.0       5.00        5.00  
is_claimed_booking            0.0       0.0       0.00        1.00

In [10]:
# Summary statistics for categorical variables
df.describe(include='object').T

count   unique  \
booking_id        1135060  1134293   
place_size        1109181        8   
service_name      1135060        4   
sub_service_name    26417        7   
extra_service       38345        6   
province          1135060        3   
district          1055083      123   
booking_date      1135060   936000   
cleaning_date     1122742    73129   
promo_code         627266    21399   
booking_status    1135060        5   
cancel_reason       29611        7   
problem             17128       38   

                                                                top     freq  
booking_id                                               201213YFJW       15  
place_size                       คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)   392132  
service_name                                      บริการทำความสะอาด  1107105  
sub_service_name                                    ไม่เกิน 40 ชิ้น     9851  
extra_service     ทำความสะอาดก่อนเข้าอยู่/หลังย้ายออก (ไม่ใช่ทำค...    17972  
province                                         กรุงเทพ และปริมณฑล   974206  
district                                             เมืองเชียงใหม่    75542  
booking_date                                    2019-02-01 00:00:00      901  
cleaning_date                                   2021-10-31 09:00:00      282  
promo_code                                                WELCOME05    55723  
booking_status                                            เสร็จสิ้น  1069849  
cancel_reason                         ผู้ให้บริการไม่สะดวกรับงานนี้     7183  
problem                             คุณภาพการให้บริการต่ำกว่า 4 ดาว     4973

<font color=#ffffff>

<b>Inferences</b>

Any variables that contain 1135060 non-null entries, indicating no missing values in the dataset.

While other variables with missing values would need to be addressed.

<div style="border-radius:10px; padding: 15px; background-color:#10041c; font-size:100%; text-align:left">

<b>Numerical Variables</b>

- __`user_id`__:
   - The customer IDs range from 1 to 395520 but not in order, helping in identifying unique customers.

- __`is_new_customer`__:
   - The average first time booking customer is approximately 1.3% of all current customers

- __`work_hour`__:
   - The average length of cleaning hours in a booking order is approximately 3.12 hours.
   - The work hour has a short range, with a minimum value of 0 and a maximum value of 12.
   - No outliers. Since the presence of outliers is indicated by a large difference between the maximum and the 75th percentile values.

- __`total_price`__:
   - The average booking total price of the products is approximately 732.85 THB.
   - The total price also shows a wide range, from -1140 THB to 10000 THB, which suggests the presence of errors or noise in the data, as negative prices don't make sense.
   - High possibility of outliers, the presence of outliers is indicated by a large difference between the maximum and the 75th percentile values.
   
- __`professional_id`__:
   - The service provider IDs range from 0 to 12719 but not in order, helping in identifying unique service providers.

- __`rating`__:
   - The average service rating is approximately 4.90 score.
   - Very high in missing values, might need to address missing values as unrated.
    
<b>Categorical Variables</b>

- __`place_size`__:
   - There are 8 unique cleaning place sizes.
   - The most frequent place size is "คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)", appearing 392,132 times.
   - There are some missing values in this column which need to be treated.

- __`cancel_reason`__:
   - Missing values here indicates that the booking is successful.
   - The most frequent cancel reason provide is "ผู้ให้บริการไม่สะดวกรับงานนี้", appearing 7,183 times

<a id="visualizations"></a>

### <b><span style='color:#ffa705'>Step 2.3 |</span><span style='color:#ffffff'> Data Visualization</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

In this step, data visualization is used to gain deeper insights into the dataset.  

Visualizing the data helps to identify patterns and trends, detect outliers and anomalies, understand relationships and correlations between variables, compare distributions across different categories, and simplify complex information for easier interpretation

By combining different types of visualizations (e.g., histograms, scatter plots, box plots, and heatmaps), we can uncover meaningful insights that might not be obvious from raw data alone.

In [11]:
def apply_dark_theme(fig, bg_color="#10041c", text_color="white"):
    fig.update_layout(
        plot_bgcolor=bg_color,       # plot area background
        paper_bgcolor=bg_color,      # outside plot background
        font=dict(color=text_color)  # all text
    )
    return fig

<a id="univariate"></a>

#### <b><span style='color:#ffffff'>Univariate Analysis (Single Variable)</span></b>
⬆️ [Table of Contents](#contents_table)

<a id="popular_services"></a>

<font color=#ffffff>

##### <b>Popular Services</b>

* `service_name`

* `sub_service_name`

* `extra_service`

In [ ]:

def get_counts(df, col, explode_delim=None):
    ser = df[col].dropna().astype(str)
    if explode_delim:
        ser = ser[ser != ''].str.split(explode_delim).explode().str.strip()
    counts = ser.value_counts().reset_index()
    counts.columns = [col, 'count']
    return counts

def plot_bar_counts(df, col, explode_delim=None, horiz=False, title=None):
    counts = get_counts(df, col, explode_delim=explode_delim)
    if horiz:
        fig = px.bar(counts, x='count', y=col,
                     orientation='h',
                     text='count',
                     title=title or f"Popular {col}",
                     color_discrete_sequence=["#F7D04F"])
        fig.update_layout(yaxis={'categoryorder':'total descending'})
    else:
        fig = px.bar(counts, x=col, y='count',
                     text='count',
                     title=title or f"Popular {col}",
                     #color_discrete_sequence=["#4A94F7"])
                     color=col,  # map color to the category
                     color_discrete_sequence=px.colors.qualitative.Pastel)  # or any palette
        fig.update_layout(xaxis_tickangle=-45)
        
    fig.update_traces(textposition='outside')
    fig.update_layout(width=700, height=400)
    fig = apply_dark_theme(fig)
    fig.show()

# Individual plots
plot_bar_counts(df, 'service_name', horiz=False, title='Popular Main Services')
plot_bar_counts(df, 'sub_service_name', horiz=False, title='Popular Sub-Services')
plot_bar_counts(df, 'extra_service', explode_delim=',', horiz=True, title='Popular Extra Services')

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/01_Popular_Main_Services.png?raw=true">
<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/02_Popular_Sub-Services.png?raw=true">
<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/03_Popular_Extra_Services.png?raw=true">

<a id="booking_geographic"></a>

<font color=#ffffff>

##### <b>Booking Geographic Distribution</b>

* `province` - Chiang Mai, Bangkok, Chonburi

* `district` - A total of 123 unique districts

In [ ]:
# Choropleth Map using Thailand's GeoJSON
gdf = gpd.read_file('C:\\Users\\Christopher French\\Downloads\\ビニート\\16-24_internship_project\\data\\geoBoundaries-THA-ADM1_simplified.geojson')

# ----------------------------------------
# 1. Map df.province to gdf.shapeName
# ----------------------------------------
province_map = {
    "เชียงใหม่": "Chiang Mai Province",
    "กรุงเทพ และปริมณฑล": "Bangkok",
    "ชลบุรี": "Chon Buri Province"
}
# Aggregate booking counts per province
province_counts = df['province'].value_counts().reset_index()
province_counts.columns = ['province', 'count']
province_counts['shapeName'] = province_counts['province'].map(province_map)

# ----------------------------------------
# 2. Merge counts with GeoDataFrame
# ----------------------------------------
gdf_merged = gdf.copy()
gdf_merged = gdf_merged.merge(province_counts[['shapeName','count']], on='shapeName', how='left')
gdf_merged['count'] = gdf_merged['count'].fillna(0)

# Highlight only the 3 provinces by keeping others small but visible
highlight = ["Chiang Mai Province", "Bangkok", "Chon Buri Province"]
gdf_merged['highlight_count'] = gdf_merged.apply(
    lambda row: row['count'] if row['shapeName'] in highlight else 1, axis=1
)
# Log scale to improve visibility
gdf_merged['log_count'] = np.log1p(gdf_merged['highlight_count'])

# ----------------------------------------
# 3. Plot choropleth map
# ----------------------------------------
fig = px.choropleth_mapbox(
    gdf_merged,
    geojson=gdf_merged.__geo_interface__,  # use __geo_interface__ directly
    locations='shapeName',
    featureidkey='properties.shapeName',
    color='log_count',
    color_continuous_scale="Viridis",
    mapbox_style="carto-positron",
    zoom=5,
    center={"lat": 15.5, "lon": 100.5},
    opacity=0.7,
    hover_name="shapeName",
    hover_data={"count": True, "log_count": False}  # show actual booking count
)

fig.update_layout(title="Booking Distribution by Province (Highlighted & Log Scale)")
#fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/04_Booking_Distribution_by_Province.png?raw=true">

<a id="cancellation_insights"></a>

<font color=#ffffff>

##### <b>Cancellation Insights</b>

* `booking_status`
    <pre>
    Status                       Count
    เสร็จสิ้น                       1069849
    ยกเลิก                        42590
    ยังไม่ระบุวันเข้าให้บริการ           11373
    รอเข้าให้บริการ                  11078
    ยังไม่มีคุณแม่บ้านกดรับงาน         170
    </pre>

* `cancel_reason`
    <pre>
    Reason                       Count
    ผู้ให้บริการไม่สะดวกรับงานนี้        7183
    ฉันต้องการเปลี่ยนวัน-เวลานัดหมาย   6839
    อื่น ๆ                         6644
    ผู้ให้บริการตอบรับช้า              3711
    ฉันต้องการเปลี่ยนผู้ให้บริการ        2618
    ฉันมีธุระด่วน                    2299
    ผู้ให้บริการแจ้งให้ฉันยกเลิก         317
    </pre>

In [ ]:
# booking_status
status_counts = df['booking_status'].value_counts().reset_index()
status_counts.columns = ['booking_status', 'count']

fig_status = px.bar(
    status_counts,
    x='booking_status',
    y='count',
    text='count',
    title='Booking Status Distribution',
    color='booking_status',
    color_discrete_sequence=px.colors.sequential.Viridis
)
fig_status.update_layout(
    template='plotly_dark',
    xaxis_title='Booking Status',
    yaxis_title='Number of Bookings'
)
#fig_status.update_layout(width=700, height=400)
fig_status = apply_dark_theme(fig_status)
fig_status.show()

# cancel_reason
cancel_counts = df['cancel_reason'].value_counts().reset_index()
cancel_counts.columns = ['cancel_reason', 'count']

fig_cancel = px.bar(
    cancel_counts,
    x='cancel_reason',
    y='count',
    text='count',
    title='Cancellation Reasons Distribution',
    color='cancel_reason',
    color_discrete_sequence=px.colors.sequential.Magma
)
fig_cancel.update_layout(
    template='plotly_dark',
    xaxis_title='Reason',
    yaxis_title='Number of Cancellations'
)
#fig_cancel.update_layout(width=700, height=400)
fig_cancel = apply_dark_theme(fig_cancel)
fig_cancel.show()

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/05_Booking_Status_Distribution.png?raw=true">
<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/06_Cancellation_Reasons_Distribution.png?raw=true">


<a id="numerical_variables"></a>

<font color=#ffffff>

##### <b>Numerical Variables</b>

To see skewness, outliers, and spending / rating distribution.

* `discount_cost`

* `credit_discount_cost`

* `discount_pct`

* `rating`

In [ ]:
rating_counts = df['rating'].value_counts(dropna=False).sort_index()

# Convert index to string, representing NaN clearly
rating_counts.index = rating_counts.index.map(lambda x: 'NaN' if pd.isna(x) else str(x))

fig = px.bar(
    rating_counts,
    x=rating_counts.values,
    y=rating_counts.index,
    orientation='h',
    title="Distribution of Ratings (Including NaN)",
    labels={'x': 'Count', 'y': 'Rating'}
)
fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/07_Ratings_Distribution.png?raw=true">

<a id="bivariate"></a>
#### <b><span style='color:#ffffff'>Bivariate Analysis (Two Variable)</span></b>
⬆️ [Table of Contents](#contents_table)

<a id="provider_income"></a>

<font color=#ffffff>

##### <b>Service Provider's Income</b>

* `work_hour`

* `additional_hour`

* `total_price`

In [ ]:
# Histogram with boxplot marginal to see distribution + outliers
fig = px.histogram(df, x='total_price', nbins=100,
                   marginal='box', title='Distribution of Total Income with Outliers',
                   labels={'total_price': 'Total Income'})
fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

# Scatterplot vs work_hour to see relation + outliers
fig = px.scatter(
    df, x='work_hour', y='total_price', title='Work Hours vs Total Income',
    labels={'work_hour': 'Work Hours', 'total_price': 'Total Income'},
    opacity=0.6
)
fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/08_Income_Distribution.png?raw=true">
<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/09_Income_by_Work_Hours.png?raw=true">

<a id="booking_status"></a>

<font color=#ffffff>

##### <b>Booking Status</b>

* `service_name` vs `booking_status`

* `province` vs `booking_status`

In [ ]:
# service_name vs booking_status
fig = px.histogram(
    df, 
    x='service_name', 
    color='booking_status', 
    barmode='group',  # side-by-side bars
    title='Booking Status per Service',
    labels={'service_name': 'Service Name', 'count': 'Number of Bookings'},
    height=500
)
fig.update_layout(xaxis_tickangle=-45)
fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()


# province vs booking_status
fig = px.histogram(
    df, 
    x='province', 
    color='booking_status', 
    barmode='group',
    title='Booking Status per Province',
    labels={'province': 'Province', 'count': 'Number of Bookings'},
    height=500
)
fig.update_layout(xaxis_tickangle=-45)
fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/10_Status_by_Service.png?raw=true">
<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/11_Status_by_Province.png?raw=true">


<a id="time-based"></a>

#### <b><span style='color:#ffffff'>Time-based Analysis</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

Ensure the date and time columns have are in datetime.

In [15]:
df['booking_date'] = pd.to_datetime(df['booking_date'], errors='coerce')
df['cleaning_date'] = pd.to_datetime(df['cleaning_date'], errors='coerce')

<a id="booking_trends"></a>

<font color=#ffffff>

##### <b>Booking Trends</b>

* `booking_date`

* `cleaning_date`

In [ ]:
# Aggregate counts per day
booking_counts = df.groupby(df['booking_date'].dt.date)['booking_id'].count().reset_index()
booking_counts.columns = ['date', 'booking_count']

cleaning_counts = df.groupby(df['cleaning_date'].dt.date)['booking_id'].count().reset_index()
cleaning_counts.columns = ['date', 'cleaning_count']

# Merge booking and cleaning counts on date
time_counts = pd.merge(booking_counts, cleaning_counts, on='date', how='outer').fillna(0)
time_counts = time_counts.sort_values('date')

fig = px.line(
    time_counts,
    x='date',
    y=['booking_count', 'cleaning_count'],
    labels={'value': 'Count', 'date': 'Date', 'variable': 'Type'},
    title='Booking vs Cleaning Counts Over Time'
)
fig.update_layout(
    xaxis_title='Date',
    yaxis_title='Number of Bookings / Cleanings',
    legend_title='Date Type'
)
fig.update_layout(width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

<img src="https://github.com/FearlessFrench/provider-segmentation/blob/main/visuals/12_Booking_and_Cleaning_Trends.png?raw=true">


<a id="data_cleaning"></a>

## <b><span style='color:#ffa705'>Step 3 |</span><span style='color:#ffffff'> Data Cleaning & Transformation</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

This step encompasses a comprehensive cleaning and transformation process to refine the dataset. It includes addressing missing values, eliminating duplicate entries, correcting anomalies in booking and behavior datasets, and other necessary adjustments to prepare the data for in-depth analysis and modeling.

<a id="missing_values"></a>

### <b><span style='color:#ffa705'>Step 3.1 |</span><span style='color:#ffffff'> Handling Missing Values</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

Determine the percentage of missing values present in each column, followed by selecting the most effective strategy to address them.

In [12]:
# Calculating the percentage of missing values for each column
missing_data = df.isnull().sum()
missing_percentage = (missing_data[missing_data > 0] / df.shape[0]) * 100
missing_percentage.sort_values(ascending=True, inplace=True)

fig = px.bar(
    x=missing_percentage.values,
    y=missing_percentage.index,
    orientation='h',
    labels={'x': 'Missing Percentage (%)', 'y': 'Columns'},
    title='Missing Values by Column',
    color=missing_percentage.values,
    color_continuous_scale="Blues"
)

fig.update_layout(yaxis=dict(tickmode='linear'), width=700, height=400)
fig = apply_dark_theme(fig)
fig.show()

<div style="border-radius:10px; padding:15px; background-color:rgb(256,12,84); font-size:100%; text-align:left; color:#ffffff;">

#### <b><font color=#ffffff>Handling Missing Values and Inconsistencies Strategy</font></b>

<font color=#ffffff>

- __problem (98.491% missing values)__
   - This column missing values indicates no problem occurs on the booking data such as "ทำความสะอาดไม่เรียบร้อย", "ทำทรัพย์สินของลูกค้าเสียหาย", "ขอเลื่อนเวลานัดหมายการให้บริการ", etc. Since this column acts like a report from support admin or a comment from customer, sometimes when booking_status is shown "ยกเลิก" but the value in problem column wasn't provided.

   - There's also a close resemblance between problem and cancel_reason like df["problem"] == "ขอเลื่อนเวลานัดหมายการให้บริการ", df["cancel_reason"] == "ฉันต้องการเปลี่ยนวัน-เวลานัดหมาย"
    
- __sub_service_name (97.67% missing values)__
   - This column acts more like a cleaning description for a booking such as ironing cloth less than 60 clothes, and bathroom size. Therefore, the missing data by this variable doesn't have much impact on the data.
   
- __cancel_reason (97.39% missing values)__
   - This column should only occurs when booking_status is "ยกเลิก". Therefore, a missing here have possible meaning of booking_status = ["เสร็จสิ้น", "รอเข้าให้บริการ", "ยังไม่ระบุวันเข้าให้บริการ", "ยังไม่มีคุณแม่บ้านกดรับงาน"]

   - Sometimes booking_status is "ยกเลิก" while cancel_reason wasn't provided.

   - Apparently, there's also inconsistency in booking_status when cancel_reason is provided: "ยกเลิก" has 29,500 rows (expected), "เสร็จสิ้น" has 106 rows (shouldn't have cancel_reason), and "ยังไม่ระบุวันเข้าให้บริการ" has 5 rows (shouldn't have cancel_reason)

- __extra_service (96.62% missing values)__
   - This column is very identical to sub_service_name such as ironing cloth less than 40 clothes, and bedsheet transport service.

- __rating (74.88% missing values)__
   - This column missing data indicate that customer didn't leave a rating (0.5 - 5.0 an increments of 0.5 is standard rating system) after the cleaning service. So, NaN is meaningful as "no feedback given".

- __discount_pct and promo_code (44.74% missing values)__
   - These columns missing data indicate that no discount apply on the booking.

- __district (7.05% missing values)__
   - This column missing data indicate that the customer didn't specify district when booking. However, the province column has no missing data since it's mandatory to specify.

- __place_size (2.28% missing values)__
   - This column missing data indicate that the customer didn't specify place_size when booking. Nevertheless, the cleaning service or booking_status can still be "เสร็จสิ้น".

- __cleaning_date (1.09% missing values)__
   - This column missing data indicate that the booking_status is very likely "ยังไม่ระบุวันเข้าให้บริการ" (11373 rows). However, there are also cases where booking_status is "ยกเลิก" (941 rows), and "รอเข้าให้บริการ" (4 rows)

Additionally, there is inconsistency between __booking_status__ and __is_claimed_booking__, __province__ and __district__.

By dealing with missing values in these columns, we aim to construct a cleaner and more reliable dataset, which is essential for achieving accurate clustering and creating an effective provider segmentation.

In [68]:
# Most Frequent District by Province
df.groupby("province")["district"].agg(lambda x: x.mode().iloc[0])

province
กรุงเทพ และปริมณฑล        เขตจตุจักร
ชลบุรี                      บางละมุง
เชียงใหม่             เมืองเชียงใหม่
Name: district, dtype: object

In [ ]:
# ----------------------------------------
# Handling Missing Data & Inconsistencies
# ----------------------------------------

# problem
# 1 = has problem, 0 = no problem
df["has_problem"] = df["problem"].notnull().astype(int)  # add indicator column 
df["problem"] = df["problem"].fillna("ไม่มีปัญหา")  # fill missing with explicit label

# sub_service_name
df["sub_service_name"] = df["sub_service_name"].fillna("ไม่มีบริการย่อย")  # fill missing with explicit label

# cancel_reason
# For rows where booking_status isn't "ยกเลิก", fill missing cancel_reason with "ไม่ใช่การยกเลิก"
df.loc[df["booking_status"] != "ยกเลิก", "cancel_reason"] = df.loc[df["booking_status"] != "ยกเลิก", "cancel_reason"].fillna("ไม่ใช่การยกเลิก")

# For rows where booking_status is "ยกเลิก" and cancel_reason is missing, fill with "ไม่ระบุสาเหตุการยกเลิก"
df.loc[(df["booking_status"] == "ยกเลิก") & (df["cancel_reason"].isna()), "cancel_reason"] = "ไม่ระบุสาเหตุการยกเลิก"

# extra_service
df["extra_service"] = df["extra_service"].fillna("ไม่มีบริการเสริม")  # fill missing with explicit label

# rating
df["rating"] = df["rating"].fillna("ไม่มีการให้คะแนน")

# discount_pct & promo_code
df["discount_pct"] = df["discount_pct"].fillna(0)  # missing means 0% discount
df["promo_code"] = df["promo_code"].fillna("ไม่มีรหัสส่วนลด")  # fill missing with explicit label

# district
df["district"] = df["district"].fillna("ไม่มีการระบุ")

# place_size
df["place_size"] = df["place_size"].fillna("ไม่มีการระบุ")

# cleaning_date
df["cleaning_date"] = df["cleaning_date"].fillna("ยังไม่ระบุวันเข้าให้บริการ")

In [70]:
# Verifying the removal of missing values
print(f"Total Rows with Missing Data: {df.isnull().sum().sum()}")

Total Rows with Missing Data: 0


<a id="duplicates"></a>

### <b><span style='color:#ffa705'>Step 3.2 |</span><span style='color:#ffffff'> Handling Duplicates</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

Recognize duplicate rows in the dataset.

In [71]:
# Finding duplicate rows (keeping all instances)
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

booking_id  user_id  is_new_customer  user_place_id  \
5850           6610      134                0              0   
5851           6610      134                0              0   
5854           6613      134                0              0   
5855           6613      134                0              0   
7866           9348     4812                1              0   
...             ...      ...              ...            ...   
1114931  25041718F3   206378                0         261081   
1117336  250420KP4J   292406                0         213403   
1117337  250420KP4J   292406                0         213403   
1122312  250425DYB5   327089                0         280979   
1122313  250425DYB5   327089                0         280979   

                                 place_size       service_name  \
5850          บ้าน 2-3 ชั้น (100-200 ตร.ม.)  บริการทำความสะอาด   
5851          บ้าน 2-3 ชั้น (100-200 ตร.ม.)  บริการทำความสะอาด   
5854          บ้าน 2-3 ชั้น (100-200 ตร.ม.)  บริการทำความสะอาด   
5855          บ้าน 2-3 ชั้น (100-200 ตร.ม.)  บริการทำความสะอาด   
7866     คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด   
...                                     ...                ...   
1114931                        ไม่มีการระบุ  บริการทำความสะอาด   
1117336       บ้าน 2-3 ชั้น (100-200 ตร.ม.)  บริการทำความสะอาด   
1117337       บ้าน 2-3 ชั้น (100-200 ตร.ม.)  บริการทำความสะอาด   
1122312  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)     บริการล้างแอร์   
1122313  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)     บริการล้างแอร์   

        sub_service_name     extra_service            province      district  \
5850     ไม่มีบริการย่อย  ไม่มีบริการเสริม           เชียงใหม่  ไม่มีการระบุ   
5851     ไม่มีบริการย่อย  ไม่มีบริการเสริม           เชียงใหม่  ไม่มีการระบุ   
5854     ไม่มีบริการย่อย  ไม่มีบริการเสริม           เชียงใหม่  ไม่มีการระบุ   
5855     ไม่มีบริการย่อย  ไม่มีบริการเสริม           เชียงใหม่  ไม่มีการระบุ   
7866     ไม่มีบริการย่อย  ไม่มีบริการเสริม  กรุงเทพ และปริมณฑล  ไม่มีการระบุ   
...                  ...               ...                 ...           ...   
1114931  ไม่มีบริการย่อย  ไม่มีบริการเสริม  กรุงเทพ และปริมณฑล    เขตบางซื่อ   
1117336  ไม่มีบริการย่อย  ไม่มีบริการเสริม  กรุงเทพ และปริมณฑล      พุทธมณฑล   
1117337  ไม่มีบริการย่อย  ไม่มีบริการเสริม  กรุงเทพ และปริมณฑล      พุทธมณฑล   
1122312  ไม่มีบริการย่อย  ไม่มีบริการเสริม  กรุงเทพ และปริมณฑล      เขตพญาไท   
1122313  ไม่มีบริการย่อย  ไม่มีบริการเสริม  กรุงเทพ และปริมณฑล      เขตพญาไท   

                booking_date        cleaning_date  is_sameday  work_hour  \
5850     2017-07-25 15:48:06  2017-08-01 08:00:00           0        2.5   
5851     2017-07-25 15:48:06  2017-08-01 08:00:00           0        2.5   
5854     2017-07-25 15:56:40  2017-08-04 07:00:00           0        2.5   
5855     2017-07-25 15:56:40  2017-08-04 07:00:00           0        2.5   
7866     2017-09-25 11:40:27  2017-09-25 15:30:00           1        2.0   
...                      ...                  ...         ...        ...   
1114931  2025-04-17 15:31:01  2025-04-18 12:00:00           0        3.0   
1117336  2025-04-20 14:56:01  2025-04-30 08:30:00           0        4.0   
1117337  2025-04-20 14:56:01  2025-04-30 08:30:00           0        4.0   
1122312  2025-04-25 20:14:06  2025-04-27 09:30:00           0        1.0   
1122313  2025-04-25 20:14:06  2025-04-27 09:30:00           0        1.0   

         additional_hour  total_price  discount_cost  credit_discount_cost  \
5850                 0.0        475.0          23.75                   0.0   
5851                 0.0        475.0          23.75                   0.0   
5854                 0.0        475.0          23.75                   0.0   
5855                 0.0        475.0          23.75                   0.0   
7866                 0.0        500.0         100.00                   0.0   
...                  ...          ...            ...                   ...   
1114931              0.0   

<div style="border-radius:10px; padding: 15px; background-color:rgb(256,12,84); font-size:100%; text-align:left">

#### <b><font color=#ffffff>Handling Duplicates Strategy</font></b>

<font color=#ffffff>
    
In the context of this project, the presence of completely identical rows, including identical booking times, suggests that these might be data recording errors rather than genuine repeated bookings. Keeping these duplicate rows can introduce noise and potential inaccuracies in the clustering.

Therefore, let's remove these completely identical duplicate rows from the dataset. Removing these rows will help in achieving a cleaner dataset, which in turn would aid in building more accurate service provider clusters based on their unique service providing behaviors.

In [72]:
# ----------------------------------------
# Handling Duplicates Data
# ----------------------------------------

# Displaying the number of duplicate rows
print(f"The dataset contains {df.duplicated().sum()} duplicate rows that need to be removed.")

# Removing duplicate rows
df.drop_duplicates(inplace=True) 

The dataset contains 402 duplicate rows that need to be removed.


In [73]:
# Getting the number of rows in the dataframe
df.shape[0]

1134658

In [74]:
df.head(1)

booking_id  user_id  is_new_customer  user_place_id  \
0         23    31251                1              0   

                           place_size       service_name sub_service_name  \
0  คอนโด 1 ห้องนอน (ไม่เกิน 40 ตร.ม.)  บริการทำความสะอาด  ไม่มีบริการย่อย   

      extra_service   province      district         booking_date  \
0  ไม่มีบริการเสริม  เชียงใหม่  ไม่มีการระบุ  2016-03-23 08:50:10   

         cleaning_date  is_sameday  work_hour  additional_hour  total_price  \
0  2016-03-26 13:00:00           0        2.0              0.0        400.0   

   discount_cost  credit_discount_cost       promo_code  discount_pct  \
0            0.0                   0.0  ไม่มีรหัสส่วนลด           0.0   

  booking_status    cancel_reason  professional_id  selected_professional_id  \
0      เสร็จสิ้น  ไม่ใช่การยกเลิก                8                         0   

   is_new_professional rating             problem  is_claimed_booking  \
0                    1    4.0  ไม่มีปัญหาเกิดขึ้น                   0   

   has_problem  
0            0

<a id="cancelled_cleaning"></a>

### <b><span style='color:#ffa705'>Step 3.3 |</span><span style='color:#ffffff'> Treating Cancelled Bookings</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

To refine our understanding of service provider behavior and preferences, we need to take into account the bookings that were cancelled.

Initially, we will identify these bookings by filtering the rows where the booking_status is "ยกเลิก". Subsequently, we will analyze these rows to understand their common characteristics or patterns.

In [75]:
df.booking_status.value_counts()

booking_status
เสร็จสิ้น                     1069548
ยกเลิก                          42489
ยังไม่ระบุวันเข้าให้บริการ      11373
รอเข้าให้บริการ                 11078
ยังไม่มีคุณแม่บ้านกดรับงาน        170
Name: count, dtype: int64

In [76]:
status_map = {
    "เสร็จสิ้น": "Completed",
    "ยกเลิก": "Cancelled",
    "ยังไม่ระบุวันเข้าให้บริการ": "Pending",
    "รอเข้าให้บริการ": "Pending",
    "ยังไม่มีคุณแม่บ้านกดรับงาน": "Pending"
}

# Filter out the rows with InvoiceNo starting with "C" and create a new column indicating the transaction status
df["status"] = df["booking_status"].map(status_map)

# Analyze the characteristics of these rows
status_counts = df["status"].value_counts(normalize=True) * 100
status_counts

status
Completed    94.261707
Cancelled     3.744653
Pending       1.993640
Name: proportion, dtype: float64

<a id="date_cleaning"></a>

### <b><span style='color:#ffa705'>Step 3.4 |</span><span style='color:#ffffff'> Correcting Date Anomalies</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

The Provider Segmentation's dataset has 2 dates: df["booking_date"] and df["cleaning_date"].

Both columns are still an "O" datatype. 

I will stick with the booking_date range because it's accurate:

- __`df["booking_date"].min()` >>> `'2016-03-23 08:50:10'`__ (The first ever booking in company)

- __`df["booking_date"].max()` >>> `'2025-05-08 15:10:48'`__ (The last date before I load the dataset)

Meanwhile cleaning_date has problem like:

- __`df["cleaning_date"].min()` >>> `'0000-00-00 00:00:00'`__

- __`df["cleaning_date"].max()` >>> `'ยังไม่ระบุวันเข้าให้บริการ'`__ (From the handling missing data step)

Sometimes, cleaning_date is also too far in the future like booking is in 2025 but cleaning date is 2568. This is because of wrong date format input by service provider. So basically, cleaning_date should happen after booking_date

In [77]:
# ----------------------------------------
# Correcting Date Anomalies
# ----------------------------------------

# Convert to datetime
df["booking_date"] = pd.to_datetime(df["booking_date"], errors="coerce")
df["cleaning_date"] = pd.to_datetime(df["cleaning_date"], errors="coerce")

# "0000-00-00 00:00:00" → becomes NaT (already fixed by errors="coerce")
# "ยังไม่ระบุวันเข้าให้บริการ" → keep as NaT (already fixed by errors="coerce")

In [78]:
# Check rows where booking_date and cleaning_date gap is > 1 year
df.loc[df["cleaning_date"] > df["booking_date"] + pd.Timedelta(days=365), "cleaning_date"]

19539     2019-10-01 09:00:00
19686     2020-12-21 10:00:00
19911     2019-06-07 12:00:00
19913     2023-09-30 16:00:00
19914     2020-08-01 12:00:00
                  ...        
1121097   2026-10-22 08:00:00
1121098   2026-11-12 08:00:00
1121099   2026-11-26 08:00:00
1121100   2026-12-10 08:00:00
1121101   2026-12-24 08:00:00
Name: cleaning_date, Length: 4172, dtype: datetime64[ns]

In [79]:
# if cleaning_date > booking_date + 365 days then it's an anomaly
df.loc[df["cleaning_date"] > df["booking_date"] + pd.Timedelta(days=365), "cleaning_date"] = pd.NaT

# if cleaning_date < booking_date then it's an anomaly
df.loc[df["cleaning_date"] < df["booking_date"], "cleaning_date"] = pd.NaT

<font color=#ffffff>

After this the cleaning_date is now:
- Invalid placeholders (__`0000-00-00`__, __`"ยังไม่ระบุวันเข้าให้บรการ"`__) → become __`NaT`__

- Wrong inputs (__`cleaning_date`__ < __`booking_date`__) → removed

- Unrealistic dates (__`booking_date`__ and __`cleaning_date`__ with more than 1 year gap) → removed

All that's left is dealing with __`NaT`__ rows in cleaning_date column.

In [80]:
df[df["cleaning_date"].isnull() == True].booking_status.value_counts()

booking_status
ยังไม่ระบุวันเข้าให้บริการ    11373
เสร็จสิ้น                      4435
ยกเลิก                         1121
รอเข้าให้บริการ                 630
Name: count, dtype: int64

<font color=#ffffff>

Rows with __`cleaning_date`__ = __`NaT`__

- ยังไม่ระบุวันเข้าให้บริการ → 11373   (Not scheduled yet, so NaT is correct)

- เสร็จสิ้น              → 4435   (Should have a date, but missing)

- ยกเลิก               → 1121   (Canceled, so NaT is fine)

- รอเข้าให้บริการ         → 630    (Pending, so NaT is fine)

Since __`cleaning_date`__ is critical (e.g. service duration, scheduling features) → Option B: drop completed bookings with NaT.

In [81]:
# ----------------------------------------
# Handling Missing Cleaning Date (เสร็จสิ้น)
# ----------------------------------------

# Option A: Keep them as NaT but flag for later.
#           Add a flag column to mark missing cleaning_date in completed bookings
#df["missing_cleaning_date_flag"] = (df["cleaning_date"].isna()) & (df["booking_status"] == "เสร็จสิ้น")

# Option B: Drop them.
#           Later analysis requires cleaning_date for completed bookings, I should drop these 4,435 rows.
df = df.drop(df[(df["cleaning_date"].isna()) & (df["booking_status"] == "เสร็จสิ้น")].index)

In [82]:
print("|---------- Booking Date Range ----------|")
print(f"{df["booking_date"].min()} to {df["booking_date"].max()}")

print("\n|--------- Cleaning Date Range ----------|")
print(f"{df["cleaning_date"].min()} to {df["cleaning_date"].max()}")

|---------- Booking Date Range ----------|
2016-03-23 08:50:10 to 2025-05-08 15:10:48

|--------- Cleaning Date Range ----------|
2016-03-26 13:00:00 to 2026-04-26 09:00:00


In [83]:
df[df["cleaning_date"].isnull() == True].booking_status.value_counts()

booking_status
ยังไม่ระบุวันเข้าให้บริการ    11373
ยกเลิก                         1121
รอเข้าให้บริการ                 630
Name: count, dtype: int64

<a id="data_consistency"></a>

### <b><span style='color:#ffa705'>Step 3.5 |</span><span style='color:#ffffff'> Ensuring Data Consistency</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

Continue from Step 3.4 of Correcting Date Anomalies, let's check for __`is_sameday`__ inconsistency.

According to Step 3.1 of Handling Missing Data & Inconsistencies, there is also inconsistency between __`booking_status`__ and __`is_claimed_booking`__, __`province`__ and __`district`__.

Ultimately, I should remove __`professional_id`__ = __`0`__ (ID used in system testing) and __`professional_id`__ = __`300`__ (temporary ID used for query sensitive service provider's data)

<a id="sameday_inconsistency"></a>

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

#### <b>Inconsistencies in `is_sameday`</b>

__`is_sameday`__ - Indicates if __`booking_date`__ and __`cleaning_date`__ happen on the same day (1 = yes, 0 = no).

In [84]:
# ----------------------------------------
# Handling Same-day Inconsistency
# ----------------------------------------

# Recompute same-day flag from the actual dates
check_sameday = (df["cleaning_date"].dt.date == df["booking_date"].dt.date).astype("Int64")

# Compare with existing is_sameday
df["sameday_mismatch"] = (df["is_sameday"] != check_sameday) & df["cleaning_date"].notna()

df["sameday_mismatch"].value_counts()

sameday_mismatch
False    1130223
Name: count, dtype: Int64

<font color=#ffffff>

With the new column __`sameday_mismatch`__ to check for mismatch in __`is_sameday`__. Hence, there are no same-day anomalies!

In [20]:
1130078 + 145

1130223

In [85]:
df["is_claimed_booking"].value_counts()

is_claimed_booking
0    1130078
1        145
Name: count, dtype: int64

In [86]:
df[df["is_claimed_booking"] == 1].booking_status.value_counts()

booking_status
เสร็จสิ้น                     127
รอเข้าให้บริการ                 9
ยังไม่ระบุวันเข้าให้บริการ      6
ยกเลิก                          3
Name: count, dtype: int64

<a id="status_inconsistency"></a>

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

#### <b>Inconsistencies between `booking_status` and `is_claimed_booking`</b>

is_claimed_booking = 1 happens only 145 times out of >1.1M rows indicating suspicious imbalance!

- Most of them are "เสร็จสิ้น" (127 rows), which makes sense (a claimed booking should usually be completed).

- But there are cases like:

    - "รอเข้าให้บริการ" (9 rows)

    - "ยังไม่ระบุวันเข้าให้บริการ" (6 rows)

    - "ยกเลิก" (3 rows)

These are logical inconsistencies, because:

- If a booking was __`"ยกเลิก"`__, __`"ยังไม่มีคุณแม่บ้านกดรับงาน"`__, and __`"ยังไม่ระบุวันเข้าให้บริการ"`__ → is_claimed_booking should be 0.

- If a booking is __`"เสร็จสิ้น"`__ and __`"รอเข้าให้บริการ"`__ → is_claimed_booking should be 1.

In [87]:
df[df["booking_status"] == "ยังไม่ระบุวันเข้าให้บริการ"].professional_id.value_counts()

professional_id
0      11372
300        1
Name: count, dtype: int64

In [88]:
# ----------------------------------------
# Handling Claimed Status Inconsistency
# ----------------------------------------

# is_claimed_booking == 0 where booking status ∈ {"ยกเลิก", "ยังไม่มีคุณแม่บ้านกดรับงาน", "ยังไม่ระบุวันเข้าให้บริการ"}
# is_claimed_booking == 1 where booking status ∈ {"เสร็จสิ้น", "รอเข้าให้บริการ"}
df.loc[df['booking_status'].isin(["ยกเลิก", "ยังไม่มีคุณแม่บ้านกดรับงาน", "ยังไม่ระบุวันเข้าให้บริการ"]), 'is_claimed_booking'] = 0
df.loc[df['booking_status'].isin(["เสร็จสิ้น", "รอเข้าให้บริการ"]), 'is_claimed_booking'] = 1

In [89]:
df["is_claimed_booking"].value_counts()

is_claimed_booking
1    1076191
0      54032
Name: count, dtype: int64

In [90]:
df[df["is_claimed_booking"] == 0]["booking_status"].value_counts()

booking_status
ยกเลิก                        42489
ยังไม่ระบุวันเข้าให้บริการ    11373
ยังไม่มีคุณแม่บ้านกดรับงาน      170
Name: count, dtype: int64

In [91]:
df[df["is_claimed_booking"] == 1]["booking_status"].value_counts()

booking_status
เสร็จสิ้น          1065113
รอเข้าให้บริการ      11078
Name: count, dtype: int64

<a id="geographic_inconsistency"></a>

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

#### <b>Inconsistencies between `province` and `district`</b>

These inconsistencies often come from:

- __Data entry errors__ (e.g. provider picked wrong province but right district).

- __ETL merge issues__ (district copied into wrong province).

- __Business logic shortcuts__ (sometimes everything near Bangkok gets lumped into "กรุงเทพ และปริมณฑล")

In [92]:
df.province.unique()

array(['เชียงใหม่', 'กรุงเทพ และปริมณฑล', 'ชลบุรี'], dtype=object)

In [93]:
print("|----- Chiang Mai District Inconsistencies -----|")
print('''พุทธมณฑล, เขตลาดกระบัง, กระทุ่มแบน, เขตราชเทวี,
เขตสวนหลวง, เขตบางรัก, เขตห้วยขวาง, ปากเกร็ด,
เขตประเวศ, เมืองชลบุรี, เมืองสมุทรปราการ, เขตบางกอกใหญ่,
คลองหลวง, เขตธนบุรี, บางละมุง, เขตสายไหม,
เขตปทุมวัน''')

print("\n|----- Bangkok District Inconsistencies -----|")
print('''เมืองเชียงใหม่, สารภี, สันกำแพง, บางละมุง, 
เมืองชลบุรี, สันทราย, ศรีราชา, แม่ริม, 
หางดง, ดอยสะเก็ด, สัตหีบ''')

print("\n|----- Chon Buri District Inconsistencies -----|")
print('''เขตห้วยขวาง, เขตภาษีเจริญ, เขตสวนหลวง, เขตทุ่งครุ, 
เขตวังทองหลาง, เขตบางแค, เขตบางรัก, เมืองนนทบุรี, 
ลำลูกกา, บางบ่อ, เขตราชเทวี, เมืองสมุทรปราการ,
สามพราน, บางใหญ่, เขตหนองแขม, เขตสาทร, 
เขตดอนเมือง, บางพลี''')

|----- Chiang Mai District Inconsistencies -----|
พุทธมณฑล, เขตลาดกระบัง, กระทุ่มแบน, เขตราชเทวี,
เขตสวนหลวง, เขตบางรัก, เขตห้วยขวาง, ปากเกร็ด,
เขตประเวศ, เมืองชลบุรี, เมืองสมุทรปราการ, เขตบางกอกใหญ่,
คลองหลวง, เขตธนบุรี, บางละมุง, เขตสายไหม,
เขตปทุมวัน

|----- Bangkok District Inconsistencies -----|
เมืองเชียงใหม่, สารภี, สันกำแพง, บางละมุง, 
เมืองชลบุรี, สันทราย, ศรีราชา, แม่ริม, 
หางดง, ดอยสะเก็ด, สัตหีบ

|----- Chon Buri District Inconsistencies -----|
เขตห้วยขวาง, เขตภาษีเจริญ, เขตสวนหลวง, เขตทุ่งครุ, 
เขตวังทองหลาง, เขตบางแค, เขตบางรัก, เมืองนนทบุรี, 
ลำลูกกา, บางบ่อ, เขตราชเทวี, เมืองสมุทรปราการ,
สามพราน, บางใหญ่, เขตหนองแขม, เขตสาทร, 
เขตดอนเมือง, บางพลี


In [94]:
# ----------------------------------------
# Handling Province-District Inconsistency
# ----------------------------------------

# Lists of inconsistent districts for each province
chiangmai_bad = ["พุทธมณฑล", "เขตลาดกระบัง", "กระทุ่มแบน", "เขตราชเทวี",
                 "เขตสวนหลวง", "เขตบางรัก", "เขตห้วยขวาง", "ปากเกร็ด",
                 "เขตประเวศ", "เมืองชลบุรี", "เมืองสมุทรปราการ", "เขตบางกอกใหญ่",
                 "คลองหลวง", "เขตธนบุรี", "บางละมุง", "เขตสายไหม",
                 "เขตปทุมวัน"]
bangkok_bad = ["เมืองเชียงใหม่", "สารภี", "สันกำแพง", "บางละมุง",
               "เมืองชลบุรี", "สันทราย", "ศรีราชา", "แม่ริม",
               "หางดง", "ดอยสะเก็ด", "สัตหีบ"]
chonburi_bad = ["เขตห้วยขวาง", "เขตภาษีเจริญ", "เขตสวนหลวง", "เขตทุ่งครุ",
                "เขตวังทองหลาง", "เขตบางแค", "เขตบางรัก", "เมืองนนทบุรี",
                "ลำลูกกา", "บางบ่อ", "เขตราชเทวี", "เมืองสมุทรปราการ",
                "สามพราน", "บางใหญ่", "เขตหนองแขม", "เขตสาทร",
                "เขตดอนเมือง", "บางพลี"]

# Set inconsistent districts to "ไม่มีการระบุ"
#df.loc[(df["province"] == "เชียงใหม่") & (df["district"].isin(chiangmai_bad)), "district"] = "ไม่มีการระบุ"
#df.loc[(df["province"] == "กรุงเทพ และปริมณฑล") & (df["district"].isin(bangkok_bad)), "district"] = "ไม่มีการระบุ"
#df.loc[(df["province"] == "ชลบุรี") & (df["district"].isin(chonburi_bad)), "district"] = "ไม่มีการระบุ"

# Easier to maintain if we add more provinces later
bad_districts = {"เชียงใหม่": chiangmai_bad,
                 "กรุงเทพ และปริมณฑล": bangkok_bad,
                 "ชลบุรี": chonburi_bad}

for province, bad_list in bad_districts.items():
    df.loc[(df["province"] == province) & (df["district"].isin(bad_list)), "district"] = "ไม่มีการระบุ"

<a id="id_inconsistency"></a>

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

#### <b>Remove Professional System / Test Artifact IDs</b>

Drop rows where service provider are 0 and 300 which are not real providers, since they would inject noise into segmentation.

- __`professional_id == 0`__ (artificial service provider for testing system).

- __`professional_id == 300`__ (temporary id for querying provider with sensitive data).

In [95]:
df[df["professional_id"].isin([0, 300]) == True].booking_status.value_counts()

booking_status
ยกเลิก                        35647
ยังไม่ระบุวันเข้าให้บริการ    11373
รอเข้าให้บริการ                 736
ยังไม่มีคุณแม่บ้านกดรับงาน      170
เสร็จสิ้น                        97
Name: count, dtype: int64

In [96]:
# ----------------------------------------
# Removing Invalid professional_id
# ----------------------------------------

# Remove system / test IDs
df = df[~df["professional_id"].isin([0, 300])]

<a id="outlier_cleaning"></a>

### <b><span style='color:#ffa705'>Step 3.6 |</span><span style='color:#ffffff'> Outlier Treatment</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

In K-Means Clustering, the algorithm is sensitive to both the scale of data and the presence of outliers, as they can significantly influence the position of centroids, potentially leading to incorrect cluster assignments. However, considering the context of this project where the final goal is to segment service provider by behavior and preferences through K-Means Clustering, it would be more prudent to address the issue of outliers __after the feature engineering phase__ where we create a customer-centric dataset. At this stage, removing outliers might eliminate valuable information that could play a crucial role in segmenting service providers later on. Therefore, we will postpone the outlier treatment and proceed to the next stage for now.

In [47]:
# Resetting the index of the cleaned dataset
df.reset_index(drop=True, inplace=True)

In [48]:
# Getting the number of rows in the dataframe
df.shape[0]

1082200

In [49]:
# Save a cleaned dataset for the next step
df.to_csv("booking_raw_cleaned.csv", index=False)

<a id="feature_engineering"></a>

## <b><span style='color:#ffa705'>Step 4 |</span><span style='color:#ffffff'> Feature Engineering</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

This step I'm going to **extract meaningful features** from service provider data to support provider segmentation models (e.g., K-Means, Hierarchical Clustering, DBSCAN).

In order to create a comprehensive service provider-centric dataset for clustering, the following features can be engineered from the available data.

In [36]:
cleaned_data = "C:\\Users\\Christopher French\\Downloads\\ビニート\\16-24_internship_project\\data\\booking_raw_cleaned.csv"

df = pd.read_csv(cleaned_data)

# After reading the cleaned CSV, convert date columns to datetime
df["booking_date"] = pd.to_datetime(df["booking_date"], errors="coerce")
df["cleaning_date"] = pd.to_datetime(df["cleaning_date"], errors="coerce")

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082200 entries, 0 to 1082199
Data columns (total 31 columns):
 #   Column                    Non-Null Count    Dtype         
---  ------                    --------------    -----         
 0   booking_id                1082200 non-null  object        
 1   user_id                   1082200 non-null  int64         
 2   is_new_customer           1082200 non-null  int64         
 3   user_place_id             1082200 non-null  int64         
 4   place_size                1082200 non-null  object        
 5   service_name              1082200 non-null  object        
 6   sub_service_name          1082200 non-null  object        
 7   extra_service             1082200 non-null  object        
 8   province                  1082200 non-null  object        
 9   district                  1082200 non-null  object        
 10  booking_date              1082200 non-null  datetime64[ns]
 11  cleaning_date             1081755 non-null  dateti

<a id="rfm_features"></a>

### <b><span style='color:#ffa705'>Step 4.1 |</span><span style='color:#ffffff'> RFM Features</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

RFM is a method used for analyzing provider value and segmenting the provider base. It is an acronym that stands for:

- __Recency (R):__ This metric indicates how recently a provider has made a purchase. A lower recency value means the provider has provided service more recently, indicating higher engagement with the company.

- __Frequency (F):__ This metric signifies how often a provider makes a service providing within a certain period. A higher frequency value indicates a provider who interacts with the customer more often, suggesting higher loyalty or satisfaction.

- __Monetary (M):__ This metric represents the total amount of money a provider has earned over a certain period. providers who have a higher monetary value have contributed more to the business, indicating their potential high lifetime value.

Together, these metrics help in understanding a provider's behavior, which is pivotal in personalizing marketing strategies and improving relation.

<a id="recency"></a>

#### <b><span style='color:#ffa705'>Step 4.1.1 |</span><span style='color:#ffffff'> Recency (R)</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

In this step, we focus on understanding how recently a service provider has complete a cleaning service. This is a crucial aspect of provider segmentation as it helps in identifying the engagement level of service providers. Here, I am going to define the following feature:

- __last_completed_cleaning_date__: The last cleaning date after the last booking date in the `df["booking_date"]` of the service provider.

- __days_since_last_service__: This feature represents the number of days that have passed since the provider's last service. A lower value indicates that the provider has provided service recently, implying a higher engagement level with the business, whereas a higher value may indicate a lapse or decreased engagement. By understanding the recency of services, businesses can tailor their marketing strategies to re-engage providers who have not provided service in a while, potentially increasing service provider retention and fostering loyalty.

In [38]:
# Use booking_date for latest_date reference
latest_date = df["booking_date"].max()
completed = df[df["booking_status"] == "เสร็จสิ้น"]

provider_data = (
    completed.groupby("professional_id")["cleaning_date"]
    .max()
    .reset_index()
    .rename(columns={"cleaning_date": "last_completed_cleaning_date"})
)
provider_data["days_since_last_service"] = (
    latest_date - provider_data["last_completed_cleaning_date"]
).dt.days

In [39]:
# provider_data now contains one row per provider
provider_data

professional_id last_completed_cleaning_date  days_since_last_service
0                   5          2022-08-05 16:00:00                     1006
1                   6          2017-07-29 13:00:00                     2840
2                   7          2017-01-21 12:00:00                     3029
3                   8          2016-04-01 13:00:00                     3324
4                   9          2018-01-01 14:30:00                     2684
...               ...                          ...                      ...
7254            12691          2025-05-08 12:30:00                        0
7255            12698          2025-05-05 19:00:00                        2
7256            12699          2025-05-05 12:30:00                        3
7257            12703          2025-05-07 09:00:00                        1
7258            12704          2025-05-08 13:30:00                        0

[7259 rows x 3 columns]

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

__Note:__ I've named the service provider-centric dataframe as __provider_data__, which will eventually contain all the provider-based features we plan to create.

<a id="frequency"></a>

#### <b><span style='color:#ffa705'>Step 4.1.2 |</span><span style='color:#ffffff'> Frequency (F)</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

In this step, I am going to create two features that quantify the frequency of a service provider's engagement with the customer:

- __total_service_provided__: This feature indicates the total number of services (`df["booking_status"]` is `"เสร็จสิ้น"`) provided across all booking. It gives an insight into the service provider's behavior in terms of the volume of service provided.

- __total_service_cancelled__: This feature indicates the total number of services (`df["booking_status"]` is `"ยกเลิก"`) cancelled across all booking.
    
This feature will be crucial in segmenting customers based on their service providing frequency, which is a key aspect in determining provider segments for targeted marketing.

In [40]:
# Calculate the total number of provided service made by each provider
total_service = (
    df[df["booking_status"] == "เสร็จสิ้น"]
    .groupby("professional_id")["booking_id"]
    .count()
    .reset_index()
    .rename(columns={"booking_id": "total_service_provided"})
)

# Calculate the total number of cancelled service made by each provider
total_cancelled = (
    df[df["booking_status"] == "ยกเลิก"]
    .groupby("professional_id")["booking_id"]
    .count()
    .reset_index()
    .rename(columns={"booking_id": "total_service_cancelled"})
)

# Merge the new features into the provider_data dataframe
provider_data = provider_data.merge(total_service, on="professional_id", how="left")
provider_data = provider_data.merge(total_cancelled, on="professional_id", how="left")

# Clean any missing values by filling with 0
provider_data["total_service_provided"] = provider_data["total_service_provided"].fillna(0).astype(int)
provider_data["total_service_cancelled"] = provider_data["total_service_cancelled"].fillna(0).astype(int)

provider_data

professional_id last_completed_cleaning_date  days_since_last_service  \
0                   5          2022-08-05 16:00:00                     1006   
1                   6          2017-07-29 13:00:00                     2840   
2                   7          2017-01-21 12:00:00                     3029   
3                   8          2016-04-01 13:00:00                     3324   
4                   9          2018-01-01 14:30:00                     2684   
...               ...                          ...                      ...   
7254            12691          2025-05-08 12:30:00                        0   
7255            12698          2025-05-05 19:00:00                        2   
7256            12699          2025-05-05 12:30:00                        3   
7257            12703          2025-05-07 09:00:00                        1   
7258            12704          2025-05-08 13:30:00                        0   

      total_service_provided  total_service_cancelled  
0                         31                      283  
1                          5                        4  
2                        415                        2  
3                          2                        0  
4                         96                        1  
...                      ...                      ...  
7254                       4                        0  
7255                       3                        0  
7256                       2                        0  
7257                       1                        0  
7258                       4                        0  

[7259 rows x 5 columns]

<a id="monetary"></a>

#### <b><span style='color:#ffa705'>Step 4.1.3 |</span><span style='color:#ffffff'> Monetary (M)</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041c; font-size:100%; text-align:left">

<font color=#ffffff>

In this step, I am going to create two features that represent the monetary aspect of customer's transactions:

- __total_revenue__: This feature represents the total amount of money earned by each provider. It is calculated as the sum of the `df["total_price"]`. This feature is crucial as it helps in identifying the total revenue generated by each provider, which is a direct indicator of a service provider's value to the business.

- __total_service_hour__: This feature represents the total service hour by each provider. It is calculated as the sum of the product of `df["work_hour"]` and `df["additional_hour"]`.

- __average_revenue__: This feature is calculated as the __total_revenue__ divided by the total claimed booking for each provider. It indicates the average revenue of a booking carried out by a provider. This metric is useful in understanding the servicing behavior of providers per booking, which can assist in tailoring marketing strategies and offers to different provider segments based on their average servicing patterns.

In [41]:
# Calculate total_revenue for each provider (sum of total_price for completed bookings)
total_revenue = (
    df[df["booking_status"] == "เสร็จสิ้น"]
    .groupby("professional_id")["total_price"]
    .sum()
    .reset_index()
    .rename(columns={"total_price": "total_revenue"})
)

# Calculate total_service_hour for each provider (sum of work_hour + additional_hour for completed bookings)
total_service_hour = (
    df[df["booking_status"] == "เสร็จสิ้น"]
    .assign(service_hour=lambda x: x["work_hour"] + x["additional_hour"])
    .groupby("professional_id")["service_hour"]
    .sum()
    .reset_index()
    .rename(columns={"service_hour": "total_service_hour"})
)

# Merge these features into provider_data
provider_data = provider_data.merge(total_revenue, on="professional_id", how="left")
provider_data = provider_data.merge(total_service_hour, on="professional_id", how="left")

provider_data["total_revenue"] = provider_data["total_revenue"].fillna(0)
provider_data["total_service_hour"] = provider_data["total_service_hour"].fillna(0)

# Calculate average_revenue (total_revenue / total_service_provided)
provider_data["average_revenue"] = provider_data.apply(
    lambda row: row["total_revenue"] / row["total_service_provided"] if row["total_service_provided"] > 0 else 0,
    axis=1
)

provider_data

professional_id last_completed_cleaning_date  days_since_last_service  \
0                   5          2022-08-05 16:00:00                     1006   
1                   6          2017-07-29 13:00:00                     2840   
2                   7          2017-01-21 12:00:00                     3029   
3                   8          2016-04-01 13:00:00                     3324   
4                   9          2018-01-01 14:30:00                     2684   
...               ...                          ...                      ...   
7254            12691          2025-05-08 12:30:00                        0   
7255            12698          2025-05-05 19:00:00                        2   
7256            12699          2025-05-05 12:30:00                        3   
7257            12703          2025-05-07 09:00:00                        1   
7258            12704          2025-05-08 13:30:00                        0   

      total_service_provided  total_service_cancelled  total_revenue  \
0                         31                      283       23863.55   
1                          5                        4        1384.44   
2                        415                        2      152059.19   
3                          2                        0         900.00   
4                         96                        1       76797.50   
...                      ...                      ...            ...   
7254                       4                        0        1669.50   
7255                       3                        0        1560.00   
7256                       2                        0        1410.00   
7257                       1                        0        1248.00   
7258                       4                        0        2040.00   

      total_service_hour  average_revenue  
0                   93.5       769.791935  
1                   10.0       276.888000  
2                  844.5       366.407687  
3                    4.5       450.000000  
4                  319.5       799.973958  
...                  ...              ...  
7254                 8.5       417.375000  
7255                 6.0       520.000000  
7256                 5.5       705.000000  
7257                 6.0      1248.000000  
7258                 8.5       510.000000  

[7259 rows x 8 columns]

<a id="type_diversity"></a>

### <b><span style='color:#ffa705'>Step 4.2 |</span><span style='color:#ffffff'> Service Type Diversity</span></b>
⬆️ [Table of Contents](#contents_table)

In [42]:
df["service_name"].value_counts()

service_name
บริการทำความสะอาด           1057001
บริการรีดผ้า                  18094
บริการทำความสะอาดห้องน้ำ       5733
บริการล้างแอร์                 1372
Name: count, dtype: int64

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

In this step, we are going to understand the diversity in the service providing behavior of providers.

- __unique_services_provided__: This feature represents the number of distinct services provided by a service provider through `df["service_name"]`. A higher value indicates that the provider has a diverse preference, providing a wide range of services, while a lower value might indicate a focused or specific preference.

In [43]:
# Calculate the number of unique services provided by each provider
unique_services = (
    df[df["booking_status"] == "เสร็จสิ้น"]
    .groupby("professional_id")["service_name"]
    .nunique()
    .reset_index()
    .rename(columns={"service_name": "unique_services_provided"})
)

# Merge into provider_data
provider_data = provider_data.merge(unique_services, on="professional_id", how="left")
provider_data["unique_services_provided"] = provider_data["unique_services_provided"].fillna(0).astype(int)

provider_data

professional_id last_completed_cleaning_date  days_since_last_service  \
0                   5          2022-08-05 16:00:00                     1006   
1                   6          2017-07-29 13:00:00                     2840   
2                   7          2017-01-21 12:00:00                     3029   
3                   8          2016-04-01 13:00:00                     3324   
4                   9          2018-01-01 14:30:00                     2684   
...               ...                          ...                      ...   
7254            12691          2025-05-08 12:30:00                        0   
7255            12698          2025-05-05 19:00:00                        2   
7256            12699          2025-05-05 12:30:00                        3   
7257            12703          2025-05-07 09:00:00                        1   
7258            12704          2025-05-08 13:30:00                        0   

      total_service_provided  total_service_cancelled  total_revenue  \
0                         31                      283       23863.55   
1                          5                        4        1384.44   
2                        415                        2      152059.19   
3                          2                        0         900.00   
4                         96                        1       76797.50   
...                      ...                      ...            ...   
7254                       4                        0        1669.50   
7255                       3                        0        1560.00   
7256                       2                        0        1410.00   
7257                       1                        0        1248.00   
7258                       4                        0        2040.00   

      total_service_hour  average_revenue  unique_services_provided  
0                   93.5       769.791935                         1  
1                   10.0       276.888000                         1  
2                  844.5       366.407687                         1  
3                    4.5       450.000000                         1  
4                  319.5       799.973958                         1  
...                  ...              ...                       ...  
7254                 8.5       417.375000                         2  
7255                 6.0       520.000000                         1  
7256                 5.5       705.000000                         2  
7257                 6.0      1248.000000                         1  
7258                 8.5       510.000000                         2  

[7259 rows x 9 columns]

<a id="behavioral_features"></a>

### <b><span style='color:#ffa705'>Step 4.3 |</span><span style='color:#ffffff'> Behavioral Features</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

<font color=#ffffff>

In this step, we aim to understand and capture the service providing patterns and behaviors of providers. These features will give us insights into the providers' preferences regarding when they like to provide service, which can be crucial information for personalizing their cleaning experience.

- __average_days_between_services__: This feature represents the average number of days a provider waits before making another cleaning service. Understanding this can help in predicting when the customer is likely to make their next cleaning service.

- __favorite_cleaning_day__: This denotes the day of the week when the service provider cleans the most. This information can help in identifying the preferred cleaning days of different provider segments, which can be used to optimize marketing strategies and promotions for different days of the week.
    
- __favorite_cleaning_hour__: This refers to the hour of the day when the service provider cleans the most. Identifying the favorite cleaning hour can aid in optimizing the timing of marketing campaigns and promotions to align with the times when different provider segments are most active.
    
By including these behavioral features in our dataset, we can create a more rounded view of our providers, which will potentially enhance the effectiveness of the clustering algorithm, leading to more meaningful provider segments.

In [44]:
# ------------------------------
# Behavioral Features
# ------------------------------

# Only use completed bookings for behavioral features
completed = df[df["booking_status"] == "เสร็จสิ้น"].copy()

# Average days between cleaning services
def avg_days_between_services(group):
    dates = group.sort_values().dropna()
    if len(dates) < 2:
        return 0
    gaps = dates.diff().dt.days.dropna()
    return gaps.mean()

avg_days = (
    completed.groupby("professional_id")["cleaning_date"]
    .apply(avg_days_between_services)
    .reset_index()
    .rename(columns={"cleaning_date": "average_days_between_services"})
)

# Favorite cleaning day
completed["cleaning_weekday"] = completed["cleaning_date"].dt.day_name()
fav_day = (
    completed.groupby("professional_id")["cleaning_weekday"]
    .agg(lambda x: x.value_counts().idxmax())
    .reset_index()
    .rename(columns={"cleaning_weekday": "favorite_cleaning_day"})
)

# Favorite cleaning hour
completed["cleaning_hour"] = completed["cleaning_date"].dt.hour
fav_hour = (
    completed.groupby("professional_id")["cleaning_hour"]
    .agg(lambda x: x.value_counts().idxmax())
    .reset_index()
    .rename(columns={"cleaning_hour": "favorite_cleaning_hour"})
)

# Merge all features into provider_data
provider_data = provider_data.merge(avg_days, on="professional_id", how="left")
provider_data = provider_data.merge(fav_day, on="professional_id", how="left")
provider_data = provider_data.merge(fav_hour, on="professional_id", how="left")

provider_data["average_days_between_services"] = provider_data["average_days_between_services"].fillna(0)
provider_data["favorite_cleaning_day"] = provider_data["favorite_cleaning_day"].fillna("Unknown")
provider_data["favorite_cleaning_hour"] = provider_data["favorite_cleaning_hour"].fillna(-1)

provider_data

professional_id last_completed_cleaning_date  days_since_last_service  \
0                   5          2022-08-05 16:00:00                     1006   
1                   6          2017-07-29 13:00:00                     2840   
2                   7          2017-01-21 12:00:00                     3029   
3                   8          2016-04-01 13:00:00                     3324   
4                   9          2018-01-01 14:30:00                     2684   
...               ...                          ...                      ...   
7254            12691          2025-05-08 12:30:00                        0   
7255            12698          2025-05-05 19:00:00                        2   
7256            12699          2025-05-05 12:30:00                        3   
7257            12703          2025-05-07 09:00:00                        1   
7258            12704          2025-05-08 13:30:00                        0   

      total_service_provided  total_service_cancelled  total_revenue  \
0                         31                      283       23863.55   
1                          5                        4        1384.44   
2                        415                        2      152059.19   
3                          2                        0         900.00   
4                         96                        1       76797.50   
...                      ...                      ...            ...   
7254                       4                        0        1669.50   
7255                       3                        0        1560.00   
7256                       2                        0        1410.00   
7257                       1                        0        1248.00   
7258                       4                        0        2040.00   

      total_service_hour  average_revenue  unique_services_provided  \
0                   93.5       769.791935                         1   
1                   10.0       276.888000                         1   
2                  844.5       366.407687                         1   
3                    4.5       450.000000                         1   
4                  319.5       799.973958                         1   
...                  ...              ...                       ...   
7254                 8.5       417.375000                         2   
7255                 6.0       520.000000                         1   
7256                 5.5       705.000000                         2   
7257                 6.0      1248.000000                         1   
7258                 8.5       510.000000                         2   

      average_days_between_services favorite_cleaning_day  \
0                         77.033333             Wednesday   
1                        118.000000              Saturday   
2                          0.323671               Tuesday   
3                          6.000000              Saturday   
4                          6.368421                Monday   
...                             ...                   ...   
7254                       1.333333                Sunday   
7255                       0.000000                Monday   
7256                       1.000000              Saturday   
7257                       0.000000             Wednesday   
7258                       0.666667                Monday   

      favorite_cleaning_hour  
0                         10  
1                         17  
2                         12  
3                         13  
4                         13  
...                      ...  
7254                      10  
7255                      15  
7256                      13  
7257                       9  
7258                      13  

[7259 rows x 12 columns]

<a id="cancellation_insights"></a>

### <b><span style='color:#ffa705'>Step 4.4 |</span><span style='color:#ffffff'> Cancellation Insights</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

<font color=#ffffff>

In this step, I am going to delve deeper into the cancellation patterns of service providers to gain insights that can enhance our provider segmentation model.

- __cancellation_frequency__: This metric represents the total number of bookings a provider has cancelled `df["booking_status"] == "ยกเลิก"`. Understanding the frequency of cancellations can help us identify providers who are more likely to cancel bookings. This could be an indicator of dissatisfaction or other issues, along with understanding their cancel reason in `df["cancel_reason"]`.

- __cancellation_rate__: This represents the proportion of bookings that a provider has cancelled out of all their bookings. This metric gives a normalized view of cancellation behavior. A high cancellation rate might be indicative of an unsatisfied provider segment. By identifying these segments, we can develop targeted strategies to improve their cleaning experience and potentially reduce the cancellation rate.

By incorporating these cancellation insights into our dataset, we can build a more comprehensive view of service provider behavior, which could potentially aid in creating more effective and nuanced provider segmentation.

In [45]:
# ------------------------------
# Cancellation Insights
# ------------------------------

# total number of cancelled bookings per provider
#cancellation_frequency = (
#    df[df["booking_status"] == "ยกเลิก"]
#    .groupby("professional_id")["booking_id"]
#    .count()
#    .reset_index()
#    .rename(columns={"booking_id": "cancellation_frequency"})
#)

# total number of bookings per provider (any status)
total_bookings = (
    df.groupby("professional_id")["booking_id"]
    .count()
    .reset_index()
    .rename(columns={"booking_id": "total_bookings"})
)

# Merge into provider dataframe
#provider_data = provider_data.merge(cancellation_frequency, on="professional_id", how="left")
provider_data = provider_data.merge(total_bookings, on="professional_id", how="left")
#provider_data["cancellation_frequency"] = provider_data["cancellation_frequency"].fillna(0).astype(int)
provider_data["total_bookings"] = provider_data["total_bookings"].fillna(0).astype(int)

# Proportion of cancelled bookings
#provider_data["cancellation_rate"] = provider_data.apply(
#    lambda row: row["cancellation_frequency"] / row["total_bookings"] if row["total_bookings"] > 0 else 0,
#    axis=1
#)

provider_data

professional_id last_completed_cleaning_date  days_since_last_service  \
0                   5          2022-08-05 16:00:00                     1006   
1                   6          2017-07-29 13:00:00                     2840   
2                   7          2017-01-21 12:00:00                     3029   
3                   8          2016-04-01 13:00:00                     3324   
4                   9          2018-01-01 14:30:00                     2684   
...               ...                          ...                      ...   
7254            12691          2025-05-08 12:30:00                        0   
7255            12698          2025-05-05 19:00:00                        2   
7256            12699          2025-05-05 12:30:00                        3   
7257            12703          2025-05-07 09:00:00                        1   
7258            12704          2025-05-08 13:30:00                        0   

      total_service_provided  total_service_cancelled  total_revenue  \
0                         31                      283       23863.55   
1                          5                        4        1384.44   
2                        415                        2      152059.19   
3                          2                        0         900.00   
4                         96                        1       76797.50   
...                      ...                      ...            ...   
7254                       4                        0        1669.50   
7255                       3                        0        1560.00   
7256                       2                        0        1410.00   
7257                       1                        0        1248.00   
7258                       4                        0        2040.00   

      total_service_hour  average_revenue  unique_services_provided  \
0                   93.5       769.791935                         1   
1                   10.0       276.888000                         1   
2                  844.5       366.407687                         1   
3                    4.5       450.000000                         1   
4                  319.5       799.973958                         1   
...                  ...              ...                       ...   
7254                 8.5       417.375000                         2   
7255                 6.0       520.000000                         1   
7256                 5.5       705.000000                         2   
7257                 6.0      1248.000000                         1   
7258                 8.5       510.000000                         2   

      average_days_between_services favorite_cleaning_day  \
0                         77.033333             Wednesday   
1                        118.000000              Saturday   
2                          0.323671               Tuesday   
3                          6.000000              Saturday   
4                          6.368421                Monday   
...                             ...                   ...   
7254                       1.333333                Sunday   
7255                       0.000000                Monday   
7256                       1.000000              Saturday   
7257                       0.000000             Wednesday   
7258                       0.666667                Monday   

      favorite_cleaning_hour  total_bookings  
0                         10             406  
1                         17               9  
2                         12             426  
3                         13               2  
4                         13              97  
...                      ...             ...  
7254                      10               4  
7255                      15               3  
7256                      13               2  
7257                       9               2  
7258                      13               4  

[7259 rows x 13 columns]

<a id="seasonality_trends"></a>

### <b><span style='color:#ffa705'>Step 4.5 |</span><span style='color:#ffffff'> Seasonality & Trends</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

<font color=#ffffff>

In this step, I will delve into the seasonality and trends in service providers' cleaning behaviors, which can offer invaluable insights for tailoring marketing strategies and enhancing provider satisfaction.

- __monthly_revenue_mean__: This is the average amount a provider earns monthly. It helps us gauge the general earning revenue of each provider. A higher mean indicates a provider who earns more, potentially showing a more active service provider, whereas a lower mean might indicate a more part-time provider.

    
- __monthly_revenue_std__: This feature indicates the variability in a service provider's monthly earning. A higher value signals that the provider's earning fluctuates significantly month-to-month, perhaps indicating sporadic large revenues. In contrast, a lower value suggests more stable, consistent earning revenues. Understanding this variability can help in crafting personalized promotions during periods they are expected to earn more.

    
- __revenue_trend__: This reflects the trend in a provider's earning over time, calculated as the slope of the linear trend line fitted to their earning data. A positive value indicates an increasing trend in earning, possibly pointing to growing loyalty or satisfaction. Conversely, a negative trend might signal decreasing interest or satisfaction, highlighting a need for re-engagement strategies. A near-zero value signifies stable spending habits. Recognizing these trends can help in developing strategies to either maintain or alter their cleaning service patterns, enhancing the effectiveness of marketing campaigns.

By incorporating these detailed insights into our provider segmentation model, we can create more precise and actionable provider groups, facilitating the development of highly targeted marketing strategies and promotions.

In [46]:
# --------------------------------------------------
# Seasonality & Trends Features for Providers
# --------------------------------------------------

# Only use completed bookings for revenue features
completed = df[df["booking_status"] == "เสร็จสิ้น"].copy()
completed["year"] = completed["cleaning_date"].dt.year
completed["month"] = completed["cleaning_date"].dt.month

# Monthly revenue per provider
monthly_revenue = (
    completed.groupby(["professional_id", "year", "month"])["total_price"]
    .sum()
    .reset_index()
    .rename(columns={"total_price": "monthly_revenue"})
)


# Monthly mean and std
monthly_stats = (
    monthly_revenue.groupby("professional_id")["monthly_revenue"]
    .agg(monthly_revenue_mean="mean", monthly_revenue_std="std")
    .reset_index()
)
monthly_stats["monthly_revenue_std"] = monthly_stats["monthly_revenue_std"].fillna(0)


# Revenue trend (slope of monthly revenue over time)
def calc_trend(revenues):
    if len(revenues) > 1:
        x = np.arange(len(revenues))
        slope, _, _, _, _ = linregress(x, revenues)
        return slope
    else:
        return 0

trend = (
    monthly_revenue.groupby("professional_id")["monthly_revenue"]
    .apply(calc_trend)
    .reset_index()
    .rename(columns={"monthly_revenue": "revenue_trend"})
)


# Merge all features into provider_data
provider_data = provider_data.merge(monthly_stats, on="professional_id", how="left")
provider_data = provider_data.merge(trend, on="professional_id", how="left")

provider_data["monthly_revenue_mean"] = provider_data["monthly_revenue_mean"].fillna(0)
provider_data["monthly_revenue_std"] = provider_data["monthly_revenue_std"].fillna(0)
provider_data["revenue_trend"] = provider_data["revenue_trend"].fillna(0)

<a id="advanced_features"></a>

### <b><span style='color:#ffa705'>Step 4.6 |</span><span style='color:#ffffff'> Advanced Provider Features</span></b>
⬆️ [Table of Contents](#contents_table)

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

<font color=#ffffff>

Let's feature engineering the following features!

- __avg_rating__ (float): from `df["rating"]`
    
- __avg_booking_per_month__ (integer): from `df["booking_date"]` where `df["is_claimed_booking"] == 1`
    
- __avg_income_per_month__ (float): from `df["total_price"]` and `df["cleaning_date"]` where `df["booking_status"] == "เสร็จสิ้น"`

- __avg_work_hour_per_month__ (integer): from `df["work_hour"]` + `df["additional_hour"]` and `df["cleaning_date"]` where `df["booking_status"] == "เสร็จสิ้น"`

- __latest_month_booking__ (integer): Total booking count from latest month `df["cleaning_date"]`

- __latest_month_rating__ (float): An average rating from the latest month `df["cleaning_date"]`

- __latest_diff_avg_booking__ (float): Example values for this feature such as -2.773536, -0.223067	, 0.344186, 0.091446, 2.660314

- __booking_ratio_latest_to_previous__ (float): A total booking ratio between the latest month and the month before in `df["cleaning_date"]`

- __work_hour_ratio_latest_to_previous__ (float): from `df["work_hour"]` + `df["additional_hour"]` ratio between the latest month and the month before in `df["cleaning_date"]`

- __total_active_days__ (integer): A provider is consider inactive if he/she has stop providing service for 90 days according to `df["booking_date"]`.

- __active_months_ratio__ (float): Example values for this feature such as 0.445870, 0.149808, 0.828884, 0.985758, 0.841626

- __booking_std__ (float): A booking standard deviation of the service provider.

- __work_hour_std__ (float): from `df["work_hour"]` + `df["additional_hour"]`

- __income_std__ (float): from df["total_price"]

- __tenures__ (integer): A total unique district count in `df["district"]` (that is not "ไม่มีการระบุ") of the service provider.

- __province__ (category): Shows most active `df["province"]` this provider is in, and also mapping to English as the following: "เชียงใหม่" to "Chiang Mai", "กรุงเทพ และปริมณฑล" to "Bangkok", and "ชลบุรี" to "Chonburi"

- __join_date__ (date): Use the first date from `df["booking_date"]` showing the provider's first join date.

In [47]:
# ------------------------------
# Advanced Provider Features
# ------------------------------

# --- Average Rating ---
def safe_float(x):
    try:
        return float(x)
    except:
        return np.nan

completed = df[df["booking_status"] == "เสร็จสิ้น"].copy()
completed["rating_num"] = completed["rating"].apply(safe_float)
avg_rating = (
    completed.groupby("professional_id")["rating_num"]
    .mean()
    .reset_index()
    .rename(columns={"rating_num": "avg_rating"})
)
provider_data = provider_data.merge(avg_rating, on="professional_id", how="left")
provider_data["avg_rating"] = provider_data["avg_rating"].fillna(0)
#provider_data["avg_rating"] = provider_data["avg_rating"].astype(float)  # keep NaN

# --- Average Booking Per Month (claimed bookings only) ---
claimed = df[df["is_claimed_booking"] == 1].copy()
claimed["year_month"] = claimed["booking_date"].dt.to_period("M")
booking_monthly = (
    claimed.groupby(["professional_id", "year_month"])["booking_id"]
    .count()
    .reset_index()
)
avg_booking_per_month = (
    booking_monthly.groupby("professional_id")["booking_id"]
    .mean()
    .reset_index()
    .rename(columns={"booking_id": "avg_booking_per_month"})
)
provider_data = provider_data.merge(avg_booking_per_month, on="professional_id", how="left")
provider_data["avg_booking_per_month"] = provider_data["avg_booking_per_month"].fillna(0).astype(int)


# --- Average Income Per Month ---
completed["year_month"] = completed["cleaning_date"].dt.to_period("M")
income_monthly = (
    completed.groupby(["professional_id", "year_month"])["total_price"]
    .sum()
    .reset_index()
)
avg_income_per_month = (
    income_monthly.groupby("professional_id")["total_price"]
    .mean()
    .reset_index()
    .rename(columns={"total_price": "avg_income_per_month"})
)
provider_data = provider_data.merge(avg_income_per_month, on="professional_id", how="left")
provider_data["avg_income_per_month"] = provider_data["avg_income_per_month"].fillna(0)

# --- Average Work Hour Per Month ---
completed["work_hour_sum"] = completed["work_hour"] + completed["additional_hour"]
work_hour_monthly = (
    completed.groupby(["professional_id", "year_month"])["work_hour_sum"]
    .sum()
    .reset_index()
)
avg_work_hour_per_month = (
    work_hour_monthly.groupby("professional_id")["work_hour_sum"]
    .mean()
    .reset_index()
    .rename(columns={"work_hour_sum": "avg_work_hour_per_month"})
)
provider_data = provider_data.merge(avg_work_hour_per_month, on="professional_id", how="left")
provider_data["avg_work_hour_per_month"] = provider_data["avg_work_hour_per_month"].fillna(0).astype(int)


# --- Latest Month Booking & Rating ---
def get_latest_month(group):
    if group["cleaning_date"].isnull().all():
        return pd.NaT
    return group["cleaning_date"].max().to_period("M")

latest_month = completed.groupby("professional_id").apply(get_latest_month).reset_index()
latest_month.columns = ["professional_id", "latest_month"]


# Booking count in latest month
completed["year_month"] = completed["cleaning_date"].dt.to_period("M")
latest_month_booking = completed.merge(latest_month, left_on=["professional_id", "year_month"], right_on=["professional_id", "latest_month"])
latest_month_booking_count = (
    latest_month_booking.groupby("professional_id")["booking_id"]
    .count()
    .reset_index()
    .rename(columns={"booking_id": "latest_month_booking"})
)
provider_data = provider_data.merge(latest_month_booking_count, on="professional_id", how="left")
provider_data["latest_month_booking"] = provider_data["latest_month_booking"].fillna(0).astype(int)


# Latest month average rating
latest_month_rating = (
    latest_month_booking.groupby("professional_id")["rating_num"]
    .mean()
    .reset_index()
    .rename(columns={"rating_num": "latest_month_rating"})
)
provider_data = provider_data.merge(latest_month_rating, on="professional_id", how="left")
provider_data["latest_month_rating"] = provider_data["latest_month_rating"].fillna(0)


# --- Latest Diff Avg Booking ---
# Difference between latest month booking and average per month
provider_data["latest_diff_avg_booking"] = provider_data["latest_month_booking"] - provider_data["avg_booking_per_month"]


# --- Booking Ratio Latest to Previous ---
def booking_ratio_func(group):
    counts = group.groupby("year_month")["booking_id"].count().sort_index()
    if len(counts) < 2:
        return 0
    return counts.iloc[-1] / counts.iloc[-2] if counts.iloc[-2] > 0 else np.nan

booking_ratio = (
    completed.groupby("professional_id").apply(booking_ratio_func)
    .reset_index()
    .rename(columns={0: "booking_ratio_latest_to_previous"})
)
provider_data = provider_data.merge(booking_ratio, on="professional_id", how="left")
provider_data["booking_ratio_latest_to_previous"] = provider_data["booking_ratio_latest_to_previous"].fillna(0)


# --- Work Hour Ratio Latest to Previous ---
def work_hour_ratio_func(group):
    sums = group.groupby("year_month")["work_hour_sum"].sum().sort_index()
    if len(sums) < 2:
        return 0
    return sums.iloc[-1] / sums.iloc[-2] if sums.iloc[-2] > 0 else np.nan

work_hour_ratio = (
    completed.groupby("professional_id").apply(work_hour_ratio_func)
    .reset_index()
    .rename(columns={0: "work_hour_ratio_latest_to_previous"})
)
provider_data = provider_data.merge(work_hour_ratio, on="professional_id", how="left")
provider_data["work_hour_ratio_latest_to_previous"] = provider_data["work_hour_ratio_latest_to_previous"].fillna(0)


# --- Total Active Days ---
def total_active_days_func(group):
    dates = group["booking_date"].sort_values().dropna().unique()
    if len(dates) < 2:
        return 0
    gaps = pd.Series(pd.to_datetime(dates)).diff().dt.days
    return gaps[gaps > 90].count() + 1  # +1 for the first active period

active_days = (
    df.groupby("professional_id").apply(total_active_days_func)
    .reset_index()
    .rename(columns={0: "total_active_days"})
)
provider_data = provider_data.merge(active_days, on="professional_id", how="left")
provider_data["total_active_days"] = provider_data["total_active_days"].fillna(0).astype(int)


# --- Active Months Ratio ---
def active_months_ratio_func(group):
    months = group["booking_date"].dt.to_period("M").nunique()
    total_months = (
        (group["booking_date"].max().to_period("M") - group["booking_date"].min().to_period("M")).n + 1
        if months > 0 else 0
    )
    return months / total_months if total_months > 0 else 0

active_months_ratio = (
    df.groupby("professional_id").apply(active_months_ratio_func)
    .reset_index()
    .rename(columns={0: "active_months_ratio"})
)
provider_data = provider_data.merge(active_months_ratio, on="professional_id", how="left")
provider_data["active_months_ratio"] = provider_data["active_months_ratio"].fillna(0)


# --- Booking Std ---
booking_std = (
    booking_monthly.groupby("professional_id")["booking_id"]
    .std()
    .reset_index()
    .rename(columns={"booking_id": "booking_std"})
)
provider_data = provider_data.merge(booking_std, on="professional_id", how="left")
provider_data["booking_std"] = provider_data["booking_std"].fillna(0)


# --- Rating Std ---
rating_std = (
    completed.groupby("professional_id")["rating_num"]
    .std()
    .reset_index()
    .rename(columns={"rating_num": "rating_std"})
)
provider_data = provider_data.merge(rating_std, on="professional_id", how="left")
provider_data["rating_std"] = provider_data["rating_std"].fillna(0)


# --- Work Hour Std ---
work_hour_std = (
    work_hour_monthly.groupby("professional_id")["work_hour_sum"]
    .std()
    .reset_index()
    .rename(columns={"work_hour_sum": "work_hour_std"})
)
provider_data = provider_data.merge(work_hour_std, on="professional_id", how="left")
provider_data["work_hour_std"] = provider_data["work_hour_std"].fillna(0)


# --- Income Std ---
income_std = (
    income_monthly.groupby("professional_id")["total_price"]
    .std()
    .reset_index()
    .rename(columns={"total_price": "income_std"})
)
provider_data = provider_data.merge(income_std, on="professional_id", how="left")
provider_data["income_std"] = provider_data["income_std"].fillna(0)


# --- Tenures (unique districts, not "ไม่มีการระบุ") ---
districts = df[df["district"] != "ไม่มีการระบุ"]
tenures = (
    districts.groupby("professional_id")["district"]
    .nunique()
    .reset_index()
    .rename(columns={"district": "tenures"})
)
provider_data = provider_data.merge(tenures, on="professional_id", how="left")
provider_data["tenures"] = provider_data["tenures"].fillna(0).astype(int)


# --- Province (most active, mapped to English) ---
province_map = {
    "เชียงใหม่": "Chiang Mai",
    "กรุงเทพ และปริมณฑล": "Bangkok",
    "ชลบุรี": "Chonburi"
}
def most_active_province(group):
    prov = group["province"].mode()
    return province_map.get(prov.iloc[0], prov.iloc[0]) if not prov.empty else "Unknown"

province = (
    df.groupby("professional_id").apply(most_active_province)
    .reset_index()
    .rename(columns={0: "province"})
)
provider_data = provider_data.merge(province, on="professional_id", how="left")


# --- Join Date (first booking_date) ---
join_date = (
    df.groupby("professional_id")["booking_date"]
    .min()
    .reset_index()
    .rename(columns={"booking_date": "join_date"})
)
provider_data = provider_data.merge(join_date, on="professional_id", how="left")

In [48]:
provider_data

professional_id last_completed_cleaning_date  days_since_last_service  \
0                   5          2022-08-05 16:00:00                     1006   
1                   6          2017-07-29 13:00:00                     2840   
2                   7          2017-01-21 12:00:00                     3029   
3                   8          2016-04-01 13:00:00                     3324   
4                   9          2018-01-01 14:30:00                     2684   
...               ...                          ...                      ...   
7254            12691          2025-05-08 12:30:00                        0   
7255            12698          2025-05-05 19:00:00                        2   
7256            12699          2025-05-05 12:30:00                        3   
7257            12703          2025-05-07 09:00:00                        1   
7258            12704          2025-05-08 13:30:00                        0   

      total_service_provided  total_service_cancelled  total_revenue  \
0                         31                      283       23863.55   
1                          5                        4        1384.44   
2                        415                        2      152059.19   
3                          2                        0         900.00   
4                         96                        1       76797.50   
...                      ...                      ...            ...   
7254                       4                        0        1669.50   
7255                       3                        0        1560.00   
7256                       2                        0        1410.00   
7257                       1                        0        1248.00   
7258                       4                        0        2040.00   

      total_service_hour  average_revenue  unique_services_provided  \
0                   93.5       769.791935                         1   
1                   10.0       276.888000                         1   
2                  844.5       366.407687                         1   
3                    4.5       450.000000                         1   
4                  319.5       799.973958                         1   
...                  ...              ...                       ...   
7254                 8.5       417.375000                         2   
7255                 6.0       520.000000                         1   
7256                 5.5       705.000000                         2   
7257                 6.0      1248.000000                         1   
7258                 8.5       510.000000                         2   

      average_days_between_services favorite_cleaning_day  \
0                         77.033333             Wednesday   
1                        118.000000              Saturday   
2                          0.323671               Tuesday   
3                          6.000000              Saturday   
4                          6.368421                Monday   
...                             ...                   ...   
7254                       1.333333                Sunday   
7255                       0.000000                Monday   
7256                       1.000000              Saturday   
7257                       0.000000             Wednesday   
7258                       0.666667                Monday   

      favorite_cleaning_hour  total_bookings  monthly_revenue_mean  \
0                         10             406           2169.413636   
1                         17               9            692.220000   
2                         12             426          13823.562727   
3                         13               2            450.000000   
4                         13              97           3657.023810   
...                      ...             ...                   ...   
7254                      10               4           1669.500000   
7255                      15               3  

<a id="export_features"></a>

### <b><span style='color:#ffa705'>Step 4.7 |</span><span style='color:#ffffff'> Export Feature Engineer Data</span></b>
⬆️ [Table of Contents](#contents_table)

In [49]:
#provider_data.to_csv("feature_engineer_data.csv", index=False)

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

<font color=#ffffff>

We've done a great job so far! We have created a dataset that focuses on our providers, using a variety of new features that give us a deeper understanding of their service providing patterns and preferences.

In [50]:
provider_data.head()

professional_id last_completed_cleaning_date  days_since_last_service  \
0                5          2022-08-05 16:00:00                     1006   
1                6          2017-07-29 13:00:00                     2840   
2                7          2017-01-21 12:00:00                     3029   
3                8          2016-04-01 13:00:00                     3324   
4                9          2018-01-01 14:30:00                     2684   

   total_service_provided  total_service_cancelled  total_revenue  \
0                      31                      283       23863.55   
1                       5                        4        1384.44   
2                     415                        2      152059.19   
3                       2                        0         900.00   
4                      96                        1       76797.50   

   total_service_hour  average_revenue  unique_services_provided  \
0                93.5       769.791935                         1   
1                10.0       276.888000                         1   
2               844.5       366.407687                         1   
3                 4.5       450.000000                         1   
4               319.5       799.973958                         1   

   average_days_between_services favorite_cleaning_day  \
0                      77.033333             Wednesday   
1                     118.000000              Saturday   
2                       0.323671               Tuesday   
3                       6.000000              Saturday   
4                       6.368421                Monday   

   favorite_cleaning_hour  total_bookings  monthly_revenue_mean  \
0                      10             406           2169.413636   
1                      17               9            692.220000   
2                      12             426          13823.562727   
3                      13               2            450.000000   
4                      13              97           3657.023810   

   monthly_revenue_std  revenue_trend  avg_rating  avg_booking_per_month  \
0          2129.786383       3.561545    5.000000                      3   
1           271.840131    -384.440000    4.500000                      2   
2          7174.030599    1214.511909    4.981949                     38   
3            70.710678     100.000000    4.500000                      2   
4          1722.928170      86.053571    4.833333                      4   

   avg_income_per_month  avg_work_hour_per_month  latest_month_booking  \
0           2169.413636                        8                     1   
1            692.220000                        5                     1   
2          13823.562727                       76                    23   
3            450.000000                        2                     1   
4           3657.023810                       15                     1   

   latest_month_rating  latest_diff_avg_booking  \
0                  0.0                       -2   
1                  0.0                       -1   
2                  5.0                      -15   
3                  5.0                       -1   
4                  0.0                       -3   

   booking_ratio_latest_to_previous  work_hour_ratio_latest_to_previous  \
0                          0.500000                            0.500000   
1                          0.250000                            0.250000   
2                          0.410714                            0.357143   
3                          1.000000                            1.250000   
4                          0.125000                            0.125000   

   total_active_days  active_months_ratio  booking_std  rating_std  \
0                  5             0.754545     4.034387    0.000000   
1                  3             0.057471     2.121320    0.000000   
2                  1             1.000000    26.078204    0.093440   
3                  1          

In [51]:
provider_data.columns

Index(['professional_id', 'last_completed_cleaning_date',
       'days_since_last_service', 'total_service_provided',
       'total_service_cancelled', 'total_revenue', 'total_service_hour',
       'average_revenue', 'unique_services_provided',
       'average_days_between_services', 'favorite_cleaning_day',
       'favorite_cleaning_hour', 'total_bookings', 'monthly_revenue_mean',
       'monthly_revenue_std', 'revenue_trend', 'avg_rating',
       'avg_booking_per_month', 'avg_income_per_month',
       'avg_work_hour_per_month', 'latest_month_booking',
       'latest_month_rating', 'latest_diff_avg_booking',
       'booking_ratio_latest_to_previous',
       'work_hour_ratio_latest_to_previous', 'total_active_days',
       'active_months_ratio', 'booking_std', 'rating_std', 'work_hour_std',
       'income_std', 'tenures', 'province', 'join_date'],
      dtype='object')

<a id="provider_description"></a>

<div style="border-radius:10px; padding: 15px; background-color: rgb(256,12,84); font-size:100%; text-align:left">

#### <b><font color=#ffffff>Provider Dataset Description</h2></b>

<font color=#ffffff>

| __Variable__                       | __Description__ |
|     :---                           |       :---      |
| __professional_id__                | Identifier uniquely assigned to each provider, used to distinguish individual providers. |
| __last_completed_cleaning_date__   | Timestamp of the last provider's cleaning date. |
| __days_since_last_service__        | The number of days that have passed since the provider's last service. |
| __total_service_provided__         | The total number of complete booking made by the provider. |
| __total_service_cancelled__        | The total number of cancel booking by the provider. |
| __total_revenue__                  | The total amount of money the provider has earn across all bookings. |
| __total_service_hour__             | The total number of service providing hour. |
| __average_revenue__                | The average money the provider has earn. |
| __unique_services_provided__       | The number of services type provided by the provider. |
| __average_days_between_services__  | The average number of days it took for the provider to provide cleaning services. |
| __favorite_cleaning_day__          | The day of the week when the provider prefers to provide service, represented categorically (Sunday, Monday, Tuesday, ..., Saturday). |
| __favorite_cleaning_hour__         | The most frequent clean service hour of the day by the provider. |
| __total_bookings__                 | Total number of bookings claimed by the service provider. |
| __monthly_revenue_mean__           | The average money earn monthly by the provider. |
| __monthly_revenue_std__            | The variability in a provider's monthly earning |
| __revenue_trend__                  | This reflects the trend in a provider's earning over time, calculated as the slope of the linear trend line fitted to their earning data. |
| __avg_rating__                     | Average service rating of the provider. |
| __avg_booking_per_month__          | Average booking per month (claimed bookings only). |
| __avg_income_per_month__           | Average income per month. |
| __avg_work_hour_per_month__        | Average work hour per month. |
| __latest_month_booking__           | Total booking from the latest month. |
| __latest_diff_avg_booking__        | Difference between latest month booking and average per month. |
| __booking_ratio_latest_to_previous__ | Booking ratio between the latest month and the month before. |
| __work_hour_ratio_latest_to_previous__ | Work hour ratio between the latest month and the month before. |
| __total_active_days__              | Total active days (threshold <= 90 days). |
| __active_months_ratio__            | Active months ratio. |
| __booking_std__                    | Booking's standard deviation. |
| __rating_std__                     | Rating's standard deviation. |
| __work_hour_std__                  | Work hour's standard deviation. |
| __income_std__                     | Income's standard deviation. |
| __tenures__                        | Total unique districts, not "ไม่มีการระบุ". |
| __province__                       | Province that the service provider stationed. |
| __join_date__                      | Join date is the first booking date. |

In [52]:
provider_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7259 entries, 0 to 7258
Data columns (total 34 columns):
 #   Column                              Non-Null Count  Dtype         
---  ------                              --------------  -----         
 0   professional_id                     7259 non-null   int64         
 1   last_completed_cleaning_date        7259 non-null   datetime64[ns]
 2   days_since_last_service             7259 non-null   int64         
 3   total_service_provided              7259 non-null   int64         
 4   total_service_cancelled             7259 non-null   int64         
 5   total_revenue                       7259 non-null   float64       
 6   total_service_hour                  7259 non-null   float64       
 7   average_revenue                     7259 non-null   float64       
 8   unique_services_provided            7259 non-null   int64         
 9   average_days_between_services       7259 non-null   float64       
 10  favorite_cleaning_day   

<a id="data_preparation"></a>

## <b><span style='color:#ffa705'>Step 5 |</span><span style='color:#ffffff'> Data Preparation for Clustering Models</span></b>
⬆️ [Table of Contents](#contents_table)

<font color=#ffffff>

Prepare the provider data for the 2nd Phase of Provider Segmentation Modelling via Clustering.

In [53]:
# Read feature engineer data
#provider_data = pd.read_csv("C:\\Users\\Christopher French\\Downloads\\ビニート\\16-24_internship_project\\data\\feature_engineer_data.csv")

In [54]:
# Reorder columns
new_order = ['professional_id', 'total_bookings', 'total_service_provided',
             'total_service_cancelled', 'avg_rating', 'total_revenue', 
             'total_service_hour', 'avg_booking_per_month', 'avg_income_per_month',
             'avg_work_hour_per_month', 'latest_month_booking', 'latest_month_rating', 
             'latest_diff_avg_booking', 'booking_ratio_latest_to_previous', 'work_hour_ratio_latest_to_previous', 
             'total_active_days', 'active_months_ratio', 'booking_std', 
             'rating_std', 'work_hour_std', 'income_std',
             'tenures', 'province', 'unique_services_provided', 
             'favorite_cleaning_day', 'favorite_cleaning_hour', 'join_date', 
             'last_completed_cleaning_date', 'days_since_last_service']
providers = provider_data[new_order]

In [55]:
# Rename columns
providers = providers.rename(columns={'total_revenue': 'total_income'})
providers = providers.rename(columns={'total_service_hour': 'total_work_hour'})
providers = providers.rename(columns={'unique_services_provided': 'total_unique_service'})

In [56]:
# Convert join_date and last_completed_cleaning_date to date only (no time)
providers['join_date'] = pd.to_datetime(providers['join_date']).dt.date
providers['last_completed_cleaning_date'] = pd.to_datetime(providers['last_completed_cleaning_date']).dt.date

In [57]:
providers

professional_id  total_bookings  total_service_provided  \
0                   5             406                      31   
1                   6               9                       5   
2                   7             426                     415   
3                   8               2                       2   
4                   9              97                      96   
...               ...             ...                     ...   
7254            12691               4                       4   
7255            12698               3                       3   
7256            12699               2                       2   
7257            12703               2                       1   
7258            12704               4                       4   

      total_service_cancelled  avg_rating  total_income  total_work_hour  \
0                         283    5.000000      23863.55             93.5   
1                           4    4.500000       1384.44             10.0   
2                           2    4.981949     152059.19            844.5   
3                           0    4.500000        900.00              4.5   
4                           1    4.833333      76797.50            319.5   
...                       ...         ...           ...              ...   
7254                        0    0.000000       1669.50              8.5   
7255                        0    0.000000       1560.00              6.0   
7256                        0    5.000000       1410.00              5.5   
7257                        0    0.000000       1248.00              6.0   
7258                        0    5.000000       2040.00              8.5   

      avg_booking_per_month  avg_income_per_month  avg_work_hour_per_month  \
0                         3           2169.413636                        8   
1                         2            692.220000                        5   
2                        38          13823.562727                       76   
3                         2            450.000000                        2   
4                         4           3657.023810                       15   
...                     ...                   ...                      ...   
7254                      4           1669.500000                        8   
7255                      3           1560.000000                        6   
7256                      2           1410.000000                        5   
7257                      2           1248.000000                        6   
7258                      4           2040.000000                        8   

      latest_month_booking  latest_month_rating  latest_diff_avg_booking  \
0                        1                  0.0                       -2   
1                        1                  0.0                       -1   
2                       23                  5.0                      -15   
3                        1                  5.0                       -1   
4                        1                  0.0                       -3   
...                    ...                  ...                      ...   
7254                     4                  0.0                        0   
7255                     3                  0.0                        0   
7256                     2                  5.0                        0   
7257                     1                  0.0                       -1   
7258                     4                  5.0                        0   

      booking_ratio_latest_to_previous  work_hour_ratio_latest_to_previous  \
0                             0.500000                            0.500000   
1                             0.250000                            0.250000   
2                             0.410714                            0.357143   
3                             1.000000                            1.250000   
4                             0.125000                            0.1250

In [58]:
# Export data for use in Clustering Models
#providers.to_csv("providers.csv", index=False)

<div style="border-radius:10px; padding: 15px; background-color: #10041cff; font-size:100%; text-align:left">

<font color=#ffffff>

#### <b>1st Phase - COMPLETED!!</b>

For __2nd Phase (New Pipeline)__, please switch to the __`provider_segmentation_clustering_real_data_v11.ipynb`__. By initializing __`providers.csv`__ data we can now start __Data Modelling & Analysis via Clustering__!

<div style="border-radius:10px; padding:15px; background-color:rgb(256,12,84); font-size:100%; text-align:left; color:#ffffff;">

<font color=#ffffff>

#### <b>Feature Extraction Insights</b>

Some interesting feature extracted for Executives Presentation on Sep 12, 2025.

In [67]:
df = pd.read_csv("C:/Users/Christopher French/Downloads/ビニート/16-24_internship_project/data/providers.csv")

In [60]:
# to clipboard (only head rows)
#df.head().to_clipboard(index=False)

In [68]:
# Display feature extract insight for presentation

# favorite_cleaning_day distribution
day_counts = df['favorite_cleaning_day'].value_counts().reset_index()

# favorite_cleaning_hour distribution
hour_counts = df['favorite_cleaning_hour'].value_counts().reset_index()

# avg_income_per_month distribution
income_counts = df['avg_income_per_month'].value_counts(bins=10).reset_index()

In [69]:
# Plotly day_counts for use in Executive presentation
fig = px.bar(
    day_counts,
    x='favorite_cleaning_day',
    y='count',
    text='count',
    title='Favorite Cleaning Day Distribution',
    subtitle='From 7,259 Providers',
    labels={'favorite_cleaning_day': 'Day of the Week', 'count': 'Number of Providers'},
    color='count',
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig.update_traces(textposition='outside')
fig.update_layout(
    xaxis={'categoryorder':'total descending'},
    yaxis_title='Number of Providers',
    xaxis_title='Favorite Cleaning Day'
)

# Apply the dark theme
fig = apply_dark_theme(fig)
fig.show()

In [70]:
# Sort by hour for a logical time-of-day progression
hour_counts = hour_counts.sort_values('favorite_cleaning_hour')

# Plotly hour_counts for use in Executive presentation
fig = px.bar(
    hour_counts,
    x='favorite_cleaning_hour',
    y='count',
    text='count',
    title='Favorite Cleaning Hour Distribution',
    subtitle='From 7,259 Providers',
    labels={'favorite_cleaning_hour': 'Hour of the Day (24h format)', 'count': 'Number of Providers'},
    color='count',
    color_continuous_scale=px.colors.sequential.Viridis
)

fig.update_traces(textposition='outside')
fig.update_layout(
    xaxis_title='Hour of the Day',
    yaxis_title='Number of Providers',
    xaxis = dict(
        tickmode = 'linear',
        dtick = 1
    )
)

# Apply the dark theme
fig = apply_dark_theme(fig)
fig.show()

In [71]:
# avg_income_per_month distribution
income_counts = df['avg_income_per_month'].value_counts(bins=10).reset_index()
income_counts.columns = ['income_range', 'count']

In [72]:
income_counts

income_range  count
0   (-45.076, 4507.5]   3633
1    (4507.5, 9015.0]   1591
2   (9015.0, 13522.5]   1033
3  (13522.5, 18030.0]    563
4  (18030.0, 22537.5]    268
5  (22537.5, 27045.0]    105
6  (27045.0, 31552.5]     43
7  (31552.5, 36060.0]     15
8  (36060.0, 40567.5]      7
9  (40567.5, 45075.0]      1

In [73]:
df.avg_income_per_month.describe()

count     7259.000000
mean      6551.654365
std       6166.400300
min          0.000000
25%       1690.807407
50%       4500.000000
75%       9801.267857
max      45075.000000
Name: avg_income_per_month, dtype: float64

In [74]:
# Define clear, round bins for income
bins = [0, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000]
labels = [f'{bins[i]:,} - {bins[i+1]:,}' for i in range(len(bins)-1)]

# Use pd.cut to create custom bins
df['income_bin'] = pd.cut(df['avg_income_per_month'], bins=bins, labels=labels, right=False, include_lowest=True)

# Get the counts for the new bins
income_counts = df['income_bin'].value_counts().reset_index()
income_counts.columns = ['income_range', 'count']

# Sort the ranges for plotting
income_counts = income_counts.sort_values('income_range').reset_index(drop=True)

# Plotly income_counts for use in Executive presentation
fig = px.bar(
    income_counts,
    x='income_range',
    y='count',
    text='count',
    title='Average Monthly Income Distribution',
    subtitle='From 7,259 Providers, Data from May 8, 2025',
    labels={'income_range': 'Average Monthly Income Range (THB)', 'count': 'Number of Providers'},
    color='count',
    color_continuous_scale=px.colors.sequential.Plasma
)

fig.update_traces(textposition='outside')
fig.update_layout(
    xaxis_title='Average Monthly Income Bins',
    yaxis_title='Number of Providers',
    xaxis_tickangle=-45
)

# Apply the dark
fig = apply_dark_theme(fig)
fig.show()